### ISSUE TITLE
cleanup when statehost is set, can crash.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1114]
trying to run 3.0.54 dev branch on redhat 8, and the cleanup fails:
```

2024-06-18 14:48:17,090 1804741 [INFO] root remove removing sarra/download_f20
Traceback (most recent call last):
  File "/home/sarra/.local/bin/sr3", line 11, in <module>
    load_entry_point('metpx-sr3==3.0.54rc1', 'console_scripts', 'sr3')()
  File "/home/sarra/.local/lib/python3.6/site-packages/sarracenia/sr.py", line 3067, in main
    gs.remove()
  File "/home/sarra/.local/lib/python3.6/site-packages/sarracenia/sr.py", line 2078, in remove
    shutil.rmtree(statefile)
  File "/usr/lib64/python3.6/shutil.py", line 477, in rmtree
    onerror(os.lstat, path, sys.exc_info())
  File "/usr/lib64/python3.6/shutil.py", line 475, in rmtree
    orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/sarra/.cache/sr3/sarra/download_f20'
Removing flow config logs...
rm: cannot remove '/home/sarra/.cache/sr3/log/post_shim_f63_01.log': No such file or directory

```

weirdly... it's fine on other platforms.

**Comment by petersilva** [comment]
branch was not what I thought it was... once corrected, problems disappeared.
