### ISSUE TITLE
Can't send to SFTP destinations that don't support FSETSTAT

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1189]
Sending to SFTP destinations that don't support FSETSTAT causes a failure:

```
[ERROR] sarracenia.flow send could not send /source/filename to inflight=None sftp://user@example.com/ /destination/filename: FSETSTAT unsupported
```

Looking at the Paramiko code revealed that FSETSTAT is used for `chmod`, `chown`, `utime` and `truncate`. 

This happens even with `timeCopy` and `permCopy` set to False, so we shouldn't be calling chmod, chown or utime.

We do call truncate in 2 places:

1) in `readlocal_write` of the Transfer class: https://github.com/MetPX/sarracenia/blob/f7563bc70c0805f18768298df5e6bef0e64a7856/sarracenia/transfer/__init__.py#L401
    - I think this is the case we're encountering, because length is set to 0. This case is for overwriting files that already exist. We want to ensure that remnants of the old file aren't left behind when the new file is smaller than the old one.
2) in the SFTP transfer class: https://github.com/MetPX/sarracenia/blob/f7563bc70c0805f18768298df5e6bef0e64a7856/sarracenia/transfer/sftp.py#L486

In the SFTP code, there's already logic to determine if a file already exists on the destination, so we could possibly do something with that to not call truncate in the case where the file doesn't already exist.

We could additionally add a try/except around the truncate call(s), but need to be careful to make sure we're not ignoring failures to truncate in cases where truncation really was needed (when a new file overwrites a larger old file).

The workaround is to use binary acceleration for all file transfers to these destinations.

**Comment by petersilva** [comment]
I think we need to wrap all the calls with try/except and emit a warning instead of having the transfer fail:

try:
    truncate/chmod/utime... whatever
except Exception as ex:
     logger.warning( "it failed : " ex )

we could also have a credentials setting "noFSETSTAT" as a flag on sftp to not even try...

It's a little project.

**Comment by petersilva** [comment]
should we have timeout(0) implement a disabling of timeouts as a side-quest on this one?

**Comment by reidsunderland** [comment]
> should we have timeout(0) implement a disabling of timeouts as a side-quest on this one?

I vote yes for this, it should be an easy change to have alarm_set to only set the alarm when timeout > 0

**Comment by petersilva** [comment]
So I have a branch that is running in testing... and I implemented a the warning thing, and the timeout disabling thing.  now with just those changes, the sender will work, but it will spit out a warning for every file sent  "warning truncate failed"...

So I implemented a *nofsetattr* as a keyword in the credentials file, and so when you declare your sftp server credentials you add that keyword, and you will no longer get any warnings.

I'm now having second thoughts... should it be a credentials keyword or an option in the sr3_options...  if people use ~/.ssh/config to store their sftp auth setup (as they should) then there is no need for an entry in the credentials.config... except this new flag... ugh... that's why I'm wondering if a normal keyword option is the better way to go.

**Comment by petersilva** [comment]
another option might be something like:

set sarracenia.transfer.sftp.Sftp.nofsetstat  on

declare it as an option in the sftp transfer protocol... hmm..
not sure what is preferable.

**Comment by petersilva** [comment]
I changed it to an option in the config file. Seems more straight-forward.

**Comment by reidsunderland** [comment]
I prefer the option in the config file, I think it's easier to find and avoids creating credentials.conf entries that we wouldn't need otherwise. 

I like `set sarracenia.transfer.sftp.Sftp.nofsetstat on`. It's a little bit cumbersome but it's an option we shouldn't need very often and makes it clear that it only applies to SFTP.

**Comment by petersilva** [comment]
need a new branch for a second try.

**Comment by reidsunderland** [comment]
I ran into this again, this time when sending to Azure blob storage via SFTP.

I reproduced the error by calling truncate from some test code:
```
Traceback (most recent call last):

  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/paramiko/sftp_file.py", line 356, in truncate
    self.sftp._request(CMD_FSETSTAT, self.handle, attr)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 907, in _convert_status
    raise IOError(text)
OSError: UnsupportedOperation: This operation is currently unsupported. -
```

And this is the log from sr3:

```
ddi-cmc-ops06: 2025-03-13 14:42:21,819 [DEBUG] sarracenia.flow send hasattr=True, thresh=0, len=1731, remote_off=0, local_off=0
ddi-cmc-ops06: 2025-03-13 14:42:21,819 [DEBUG] sarracenia.transfer.sftp put  local_file=FXCN01_CWHF_130642___17789:... remote_file=FXCN01_CWHF_130642___17789 local_offset=0 remote_offset=0 length=0
ddi-cmc-ops06: 2025-03-13 14:42:21,875 [DEBUG] sarracenia.transfer readlocal_write sr_proto readlocal_write
ddi-cmc-ops06: 2025-03-13 14:42:21,875 [DEBUG] sarracenia.transfer local_read_open sr_proto local_read_open getcwd=/apps/sarra/public_data/... self.cwd=/incoming/20250313/...
ddi-cmc-ops06: 2025-03-13 14:42:21,875 [DEBUG] sarracenia.transfer read_write sr_proto read_write
ddi-cmc-ops06: 2025-03-13 14:42:21,889 [ERROR] sarracenia.flow send could not send /apps/sarra/public_data//20250313/.../FXCN01_CWHF_130642___17789:... to inflight=None sftp://user@destination.ca /incoming/20250313/.../FX/CWHF/06 ... FXCN01_CWHF_130642___17789: UnsupportedOperation: This operation is currently unsupported. - RequestId:<removed> Time:2025-03-13T14:42:21.8816712Z
```

I'm not 100% sure that it's actually truncate causing the issue, it could one of the other operations that I listed in the original post. It would also be helpful to have debug log messages with `exc_info=True` in all of these cases:

https://github.com/MetPX/sarracenia/blob/3234451dad8d101e717d11f1677d041faa86adc9/sarracenia/flow/__init__.py#L2681-L2783

**Comment by andreleblanc11** [comment]
I just ran into this problem with another sender. Using a binary accelerator for this case did not work (scp). The remote system doesn't allow it 🫤 . So it's only a case-by-case work-around.

```
debug2: channel 0: request exec confirm 1
debug2: channel_input_open_confirmation: channel 0: callback done
debug2: channel 0: open confirm rwindow 0 rmax 32768
debug1: Remote: This system only accepts sftp subsystem requests
```

** UPDATE **

I was able to bypass this by passing the `-s` option to the `scp` command, i.e. `accelScpCommand /usr/bin/scp -s %s %d`.

The `-s` option is only available in version 8.7 of SSH (Ubuntu 22.04 and above) 
https://www.openssh.com/txt/release-8.7#:~:text=SFTP%20support%20may,unavailable%20or%20incompatible.)#:~:text=SFTP%20support%20may,unavailable%20or%20incompatible

**Comment by petersilva** [comment]
I have cherry-picked the old patch (higher in the thread eaa99e25c79e2689bee5df8378f5b6fe0403c8aa) and then merged into the current tree for a new branch that adds *nofsetstat* option, because that's what the notes about not merging the original PR seemed to say was needed.  so now there is a new patch ( 75ba3f6bdb4c5fefa7ccdc12e5b8d5c41a630d81 ) for that.  But I have no easy way to test it.  the branch is called issue1189_try2.

I'm running through flow tests now, will let you know if it passes... then somebody can try it.

**Comment by andreleblanc11** [comment]
I ran the branch on my test environment and had to make a few small changes (https://github.com/MetPX/sarracenia/commit/98df09464d11d811273fc4c74944ff3ff519b9bd). There's a truncate located in the `readwrite_local` that wasn't covered. Once I added nofsetstat to there, I was able to transfer files from my test. There was also a signal_alarm that I corrected from previous changes.

I haven't ran the flow tests myself yet.

**Comment by reidsunderland** [comment]
Closing. We're using `nofsetstat` in a few configs on ops and it works.
