### ISSUE TITLE
paramiko dependency for pip install?

### ISSUE THREAD

**Issue by douglatornell** [MetPX/sarracenia#123]
`sr_subscribe` fails after `pip install metpx-sarracenia` with `ModuleNotFoundError` for `paramiko` (commands, output, and traceback below). After installing `paramiko` into the environment all is good.

So, it looks to me like `paramiko` needs to be added to the `install_requires` list in `setup.py`, but I'm not sure how that will interact with other aspects of your packaging setup. I'm happy to provide a pull request though, if you want me to.

Commands, output, and traceback showing failure:
```
$ pip install metpx-sarracenia
Collecting metpx-sarracenia
  Downloading https://files.pythonhosted.org/packages/17/e0/06c845b27c6369beff36b7a9bf1ad52635890ae39499e9c5faa718fea750/metpx_sarracenia-2.18.11b6-py3-none-any.whl (343kB)
    100% |████████████████████████████████| 348kB 18.3MB/s 
Requirement already satisfied: psutil in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from metpx-sarracenia) (5.4.8)
Requirement already satisfied: watchdog in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from metpx-sarracenia) (0.8.3)
Requirement already satisfied: netifaces in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from metpx-sarracenia) (0.10.7)
Requirement already satisfied: amqplib in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from metpx-sarracenia) (1.0.2)
Requirement already satisfied: humanize in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from metpx-sarracenia) (0.5.1)
Requirement already satisfied: appdirs in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from metpx-sarracenia) (1.4.3)
Requirement already satisfied: PyYAML>=3.10 in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from watchdog->metpx-sarracenia) (3.13)
Requirement already satisfied: argh>=0.24.1 in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from watchdog->metpx-sarracenia) (0.26.2)
Requirement already satisfied: pathtools>=0.1.1 in /media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages (from watchdog->metpx-sarracenia) (0.1.2)
Installing collected packages: metpx-sarracenia
Successfully installed metpx-sarracenia-2.18.11b6
(/media/doug/warehouse/conda_envs/sarracenia) MEOPAR$  sr_subscribe -h
Traceback (most recent call last):
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_subscribe.py", line 57, in <module>
    from sr_cache           import *
ModuleNotFoundError: No module named 'sr_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_consumer.py", line 36, in <module>
    from sr_amqp           import *
ModuleNotFoundError: No module named 'sr_amqp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/doug/warehouse/conda_envs/sarracenia/bin/sr_subscribe", line 7, in <module>
    from sarra.sr_subscribe import main
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_subscribe.py", line 67, in <module>
    from sarra.sr_consumer  import *
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_consumer.py", line 43, in <module>
    from sarra.sr_config   import *
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_config.py", line 51, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
(/media/doug/warehouse/conda_envs/sarracenia) MEOPAR$ sr_subscribe list plugins
Traceback (most recent call last):
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_subscribe.py", line 57, in <module>
    from sr_cache           import *
ModuleNotFoundError: No module named 'sr_cache'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_consumer.py", line 36, in <module>
    from sr_amqp           import *
ModuleNotFoundError: No module named 'sr_amqp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/media/doug/warehouse/conda_envs/sarracenia/bin/sr_subscribe", line 7, in <module>
    from sarra.sr_subscribe import main
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_subscribe.py", line 67, in <module>
    from sarra.sr_consumer  import *
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_consumer.py", line 43, in <module>
    from sarra.sr_config   import *
  File "/media/doug/warehouse/conda_envs/sarracenia/lib/python3.7/site-packages/sarra/sr_config.py", line 51, in <module>
    import paramiko
ModuleNotFoundError: No module named 'paramiko'
```

**Comment by petersilva** [comment]
yes paramiko is required now, but is not listed as a dependency.

The old versions of ubuntu don´t install the correct paramiko when it is listed as a dependency, and even older versions will not install at all.  So we arrange for installation of paramiko separately.  You can see that in the install guide that references ubuntu 12.04, where specific versions must be used.
Paramiko used to be optional, but the code changed at some point, and now it absolutely depends on it.

We still have some old systems we need to support for now.  

I changed the install document to advise installation of paramiko before the package itself.

**Comment by petersilva** [comment]
We will likely add it as a formal dependency in the next year or two, when we can drop support for some older OS versions.

**Comment by douglatornell** [comment]
Thanks for the explanation. I figured there might be some deeper packaging issues involved. A note in the docs sounds like the best possible resolution at the moment.
