### ISSUE TITLE
new_mtime references before assignment

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1262]
When a mtime is not in msg, new_mtime never gets set.

```
Traceback (most recent call last):
  File "/net/local/home/sunderlandr/sr3/sarracenia/instance.py", line 276, in <module>
    i.start()
  File "/net/local/home/sunderlandr/sr3/sarracenia/instance.py", line 267, in start
    self.running_instance.run()
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 608, in run
    self.work()
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 1184, in work
    self.do()
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 1174, in do
    self.do_download()
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 1871, in do_download
    if not self.file_should_be_downloaded(msg):
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 1501, in file_should_be_downloaded
    if new_mtime <= old_mtime:
UnboundLocalError: local variable 'new_mtime' referenced before assignment
```

**Comment by petersilva** [comment]
ugh... I tried out three different approaches and picked one.  I actually think this came out of a bad merge.
the indenting got messed up vs. the original branch... I didn't look to confirm though ... so I could be making it up.  Anyways PR incoming...

**Comment by reidsunderland** [comment]
I wasn't quite sure what the intended behaviour was, so I didn't want to attempt fixing it myself and screwing up the logic :)

(edit: I know we don't want to re-download files that haven't changed at the source, but I mean I wasn't sure of the exact order of the checks or whihc check was supposed to be done first, or how to handle cases where certain values weren't available)
