### ISSUE TITLE
How to deal with sundew pattern matching when filename is ambiguous

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#1299]
I've been working on migrating Sundew feeds to sr3 and have encountered a problem when a filename doesn't have enough sundew parameters in it. 

## Example

We have a bulletin that is coming in with a quasi-ambiguous filename.

```
fq20qx.191324^
```

In our configuration (in my use case a *sarra* config), we want to download the data with the sundew pattern matching.

```
directory               ${PBD}/${YYYYMMDD}/SOMETHING/BULLETINS/${T1}${T2}/${CCCC}/${GG}
```

However, because the filename doesn't contain any of the information requested in `directory`, the config will crash

```
2024-11-19 19:14:03,343 [DEBUG] sarracenia.flow filter  urlToMatch: http://my-server/20241119/source/of/data/fq20qx.191324^
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 276, in <module>
    i.start()
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 267, in start
    self.running_instance.run()
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 600, in run
    self.filter()
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 1068, in filter
    self.updateFieldsAccepted(m, url, pattern, maskDir,
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 964, in updateFieldsAccepted
    new_dir = self.o.sundew_dirPattern(pattern, urlstr, tfname, new_dir)
  File "/usr/lib/python3/dist-packages/sarracenia/config/__init__.py", line 2233, in sundew_dirPattern
    nddword += self.sundew_matchPattern(BN, EN, BP, dwword, dwword)
  File "/usr/lib/python3/dist-packages/sarracenia/config/__init__.py", line 2257, in sundew_matchPattern
    elif keywd[:6] == "{CCCC}": return EN[1] + keywd[6:]
IndexError: list index out of range
```

***

This feature is necessary in my opinion, because we have lots of feeds from Sundew where files come in without a clear filename.
In sundew, I think the code looks at the file contents directly to determine the filename, when the type is `bulletin-file`.

**Comment by andreleblanc11** [comment]
## Possible solution
- When the filename doesn't comply, ignore resolving the pattern. 
   - Add another call to `updateFieldsAccepted` after calling the `after_accept` plugins
   - https://github.com/MetPX/sarracenia/blob/a3f30e279d526eb822dd2144de3f33a4b82a2227/sarracenia/flow/__init__.py#L1103-L1110

**Comment by petersilva** [comment]
things to keep in mind...  on Sundew, there were two kinds of clusters, so two varieties of *sundew_extension*: "file" clusters ... that replaced PDS file feeds, and "Bulletin" feeds that replaced AM/Tandem...

* the "file" filenames have 5 colon separated fields.
* the "bulletin" filenames have 6 colon separated fields.

That's just how it was. I think the extra field is in the middle somewhere, and it is the bulletin priority number in the range 1 to 5.

**Comment by petersilva** [comment]
Are you sure there is a sundew_extension with this file? It would be set by the receiver that created the original message.  you may want to dump the message content and confirm the 'sundew_extension' field content.

**Comment by petersilva** [comment]
oh... SOMETHING in your example... should be ${SOURCE}

**Comment by petersilva** [comment]
BULLETINS in the example should be either WMO-BULLETINS or MSC-BULLETINS... I think... it depends on line termination... do these files'  lines end in just line feeds ? or are they &lt;cr>&lt;cr>&lt;lf> ?

**Comment by petersilva** [comment]
the filenames are not "ambiguous"... they just don't supply the information you want.  They are not helpful... but ambiguous would mean they leave you with several options and you aren't sure which one to pick... in this case... it leaves you with thousands of options... it's really the information you want just is not there at all (in the filename.)

**Comment by petersilva** [comment]
Where are these files coming from... is this the initial ingest into sarra ? or has a watch or something seen them upstream?

**Comment by andreleblanc11** [comment]
There's a watch process that see's the files upstream and then posts them to the sarra.
There's also no `sundew_extension` that I can find from the messages coming from the watch (although we don't have debug enabled on the config, and its also not our system).
`grep sundew /etc/sarra/bullprep/watch/bullprep-transmit.conf` confirms this theory.

```
2024-11-20 05:10:36,062 [INFO] post_log notice=20241120051036.0614514351 sftp://sarra@source-server/ /apps/bullprep/fcsts/transmit/uplink-transmit/fq20vr.200510^vr headers={'to_clusters': 'DDSR.CMC,DDSR.EDM,DDI.CMC,DDI.EDM', 'rename': '/BULLPREP/WVR/TRANSMIT/fq20vr.200510^vr', 'mtime': '20241120051031.340570211', 'atime': '20241120051035.512541533', 'mode': '666', 'parts': '1,724,1,0,0', 'sum': 'd,f510c99acca6559061a9fccf5caff760'}
```

To answer your other question, the bulletin ends in a line feed.

```
'FQCN20 CWVR 201355 CCA\nCORRECTED MARINE WEATHER STATEMENT FOR THE PACIFIC WATERS ISSUED BY\nENVIRONMENT CANADA AT 5:55 A.M. PST WEDNESDAY 20 NOVEMBER 2024.\n\nA 954 MB LOW PRESSURE CENTER WILL SLOWLY TRACK NORTHWARD ACROSS\nEXPLORER TODAY BEFORE GRADUALLY MOVING WEST OF THE REGION ON\nTHURSDAY.\n\nAHEAD OF THE LOW, STORM TO HURRICANE FORCE SOUTHEASTERLY WINDS OVER\nEXPLORER, WEST COAST VANCOUVER ISLAND AND CENTRAL WATERS WILL EASE TO\nGALE TO STORM FORCE THIS EVENING, AND THEN TO STRONG SOUTHERLIES ON\nTHURSDAY.\n\nOVER NORTHERN WATERS, GALE FORCE NORTHEASTERLIES WILL CONTINUE TODAY\nAND TONIGHT BEFORE GRADUALLY EASING ON THURSDAY.\n\nACROSS THE INNER SOUTH COAST, GALE FORCE SOUTHEASTERLIES WILL EASE\nTHIS AFTERNOON THROUGH THE EVENING.\n\nADDITIONALLY, GALE FORCE OUTFLOW WINDS WILL CONTINUE TODAY AND\nTHURSDAY THROUGH MAINLAND INLETS OF THE NORTH AND CENTRAL COAST.\n\nHIGH SEAS NEAR 8 TO 10 METRES WILL CONTINUE TODAY WEST OF VANCOUVER\nISLAND BEFORE COMING DOWN THIS EVENING.\n\n\n\n\nEND/\n'
```

Another possible solution would be to first download the files with the wrong filename somewhere without the sundew pattern and then call https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/rename/raw2bulletin.py ( so a `cvt_*` sarra config). 

UPDATE: This solution does not work.

**Comment by petersilva** [comment]
ok... so, we have options... 

* watch maybe should be assigning a sundew_extension if you are expecting to do processing on that.  Still need a sarra plugin to do the renaming... and other stuff.
* the watch itself could have a plugin that would read the file, and you could set *relPath* to the name you want to download to, and "retrievePath" to the suboptimal name that has appeared.  A normal Sarra would just download normally and naturally rename it (since the relPath is set to what you want already.)

so for the latter option (plugin for watch)... you read the first 80 bytes of the file, figure out the AHL from there... and determine a file name from that... 

The file is already getting read anyways to calculate the checksum, so it's not going to cost anything since the file is in memory anyways.  

I guess the main argument against using watch is that it's a single instance, so if the watch is too busy... it's a (slightly) bad idea to be reading files twice... 

I feel like a watch plugin is neater... but I dunno...

**Comment by petersilva** [comment]
spelling it out a little more... the python after_accept would open the file, read the first 80 bytes and match 
```

FQCN20 CWVR 201355 CCA   -> TT=FQ, AA=CN, ii=20, CCCC=CWVR,   GGGGGG=201355  BBB=CCA

```
```python

m['retrievePath'] = m['relPath']
m['relPath'] = f"MSC-BULLETINS/{TT}/{CCCC}/{TT}{AA}{ii}_{CCCC}_{GGGGGG}_{BBB}.txt"

```
so sarra... by default will retrieve from retrievePath... and maybe in the sarra config

```

mirror on
directory ${PBD}/${YYYYMMDD}/${SOURCE}


```
and it will put the right tree there by copying from relPath.

This is one way to do it anyways...

**Comment by petersilva** [comment]
Added a bug tag because crashing with stack traces is bad.  We should deal with this more elegantly.

**Comment by petersilva** [comment]
discussion in dev meeting:

* This crash should be handled so it doesn't fail.
  * mark the message bad? (reject it ) log error, perma-fail.

* before_accept, or after_gather ... an earlier entry point that would allow the variables to be set properly.
  *  plugin here will allows the filenames to be adjusted so T1 T2 CCCC exist  when new fields get assigned.

**Comment by andreleblanc11** [comment]
I've found out that the `after_gather` fix that was added in the bulletin renamer does not work unless we can receive the file contents via the message (data being inline).

The problem is that we are assigning a new value to the filename in `relPath`, but this doesn't make sense because `relPath` is also being used to fetch the file, which won't exist if we assign it the new filename.

https://github.com/MetPX/sarracenia/blob/731224357e62cb6b06180dafbfc07b2e0772145b/sarracenia/flowcb/rename/raw2bulletin.py#L169-L172

```
2025-01-27 13:58:30,403 [DEBUG] sarracenia.flow download Beginning fetch of http://ddi-cmc-ops03.cmc.ec.gc.ca//20250127/MSC-DMS-STAGE/PRODUCT3-MT/13/MTCN06_CWUL_271358___00001 0-428 into MTCN06_CWUL_271358___00001.tmp 0-428
# 20250127/MSC-DMS-STAGE/PRODUCT3-MT/13/MTCN06_CWUL_271358___00001 doesn't exist.
```

I've tried changing this by assigning `msg['new_file'] = new_file` and `msg['new_dir'] = msg['relPath']` with `msg.updatePaths(self.o, msg['new_dir'], msg['new_file'])`, but that just made the files being downloaded to not be renamed.

The AM flow test had passed during the time I made the PR, only because it receives the data inline in the message ☹

**Comment by petersilva** [comment]
maybe try msg['rename'] ?

**Comment by andreleblanc11** [comment]
That worked

**Comment by petersilva** [comment]
I'm not sure if that is a good thing... I was hoping to get rid of *rename* some day...
