### ISSUE TITLE
watch crash when trying to post unreadable file.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#1300]
![image](https://github.com/user-attachments/assets/803bb089-6a48-42df-acd7-8dfa1163dcf0)

snapshot is for v2, but I think the same will happen with v3.  need to handle failure to open file for checksumming.

**Comment by petersilva** [comment]
reproduced on sr3:
```
2024-11-19 16:54:57,399 [ERROR] sarracenia.flow gather flowCallback plugin <bound method File.gather of <sarracenia.flowcb.gather.file.File object at 0x7f051f125480>> crashed: [Errno 13] Permission denied: '/home/peter/sarra_devdocroot/downloaded_by_sub_amqp/unreadable'
2024-11-19 16:54:57,399 [DEBUG] sarracenia.flow gather details:
Traceback (most recent call last):
  File "/home/peter/sr3/sarracenia/flow/__init__.py", line 1123, in gather
    retval = p(self.o.batch-so_far)
  File "/home/peter/sr3/sarracenia/flowcb/gather/file.py", line 726, in gather
    messages.extend(self.watch_dir(d))
  File "/home/peter/sr3/sarracenia/flowcb/gather/file.py", line 670, in watch_dir
    return self.walk(sld)
  File "/home/peter/sr3/sarracenia/flowcb/gather/file.py", line 577, in walk
    messages.extend(self.post1file(path, sarracenia.stat(path)))
  File "/home/peter/sr3/sarracenia/flowcb/gather/file.py", line 397, in post1file
    messages.extend(self.post_file(path, lstat))
  File "/home/peter/sr3/sarracenia/flowcb/gather/file.py", line 157, in post_file
    msg = sarracenia.Message.fromFileData(path, self.o, lstat)
  File "/home/peter/sr3/sarracenia/__init__.py", line 666, in fromFileData
    m.computeIdentity(path, o)
  File "/home/peter/sr3/sarracenia/__init__.py", line 520, in computeIdentity
    fp = open(path, 'rb')
PermissionError: [Errno 13] Permission denied: '/home/peter/sarra_devdocroot/downloaded_by_sub_amqp/unreadable'
```

**Comment by petersilva** [comment]
note... it crashes watch entirely on v2... it just produces a stack trace and keeps going on sr3.

**Comment by petersilva** [comment]
put v2only and v3only labels because will fix at v3... but not v2... so eventually it will be v2only and *wontfix* ... but need to fix the v3 part first.
