### ISSUE TITLE
sr3 sender fails to post message when post_exchangeSplit is in use and the incoming message does not have a checksum

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1322]
```
Traceback (most recent call last):
-  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 1253, in post
-    p(self.worklist)
-  File "/usr/lib/python3/dist-packages/sarracenia/flowcb/post/message.py", line 40, in post
-    if all_good and hasattr(self.poster,'putNewMessage') and self.poster.putNewMessage(m):
-  File "/usr/lib/python3/dist-packages/sarracenia/moth/amqp.py", line 665, in putNewMessage
-    idx = sum( bytearray(body['identity']['value'],
-KeyError: 'identity'
```

https://github.com/MetPX/sarracenia/blob/a4af0e2c21f211e1d993c3a183b8eed63dbfb09c/sarracenia/moth/amqp.py#L675-L682

In a sender, we should probably ensure that all messages have an identity. If we receive one that doesn't have identity, we should calculate it.

**Comment by reidsunderland** [comment]
I wrote a plugin that seems to fix/workaround the problem:

```python
#!/usr/bin/python3
"""
If identity is missing from the message, calculate and add it.
"""

from sarracenia.flowcb import FlowCB
import sarracenia
import datetime, logging
import os

logger = logging.getLogger(__name__)

class Fix_missing_identity(FlowCB):

    def __init__(self, options) :
        super().__init__(options,logger)

    def after_accept(self, worklist):
        for msg in worklist.incoming:
            if 'identity' not in msg:
                local_path = 'unknown'
                ident = {'method': 'cod', 'value': self.o.identity_method}

                try:
                    local_path = self.o.baseDir + '/' + msg['relPath']
                    local_identity = sarracenia.identity.Identity.factory(self.o.identity_method)
                    local_identity.update_file(local_path)
                    ident = {'method': self.o.identity_method, 'value': local_identity.value}
                except Exception as e:

                    logger.warning(f"Could not calculate identity {e}, setting message identity to {ident}")

                logger.debug(f"set identity to {ident}")

                msg['identity'] = ident

```

**Comment by petersilva** [comment]
uh... that was one of the major changes last year... identity became optional. We should fix the code to allow identity to be missing.

**Comment by reidsunderland** [comment]
- In a sender, I think we should calculate the checksum if it's missing. We have the file, so we should try to post a message with as much information as possible. @petersilva said it would be best to have an option to disable this for performance reasons
- We should be able to use post_exchangeSplit without identity in a message. If identity is missing, we should have an alternative (use the filename, relPath, something else?)

**Comment by petersilva** [comment]
relevant background:
* https://github.com/MetPX/sarracenia/issues/504
* https://github.com/MetPX/sarracenia/issues/547

**Comment by petersilva** [comment]
I will work on this... need to change how post_exchangeSplit works anyways.
