### ISSUE TITLE
Problems with the rename option

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1340]
# Part 1
The `rename` option does not seem to work in a sarra.

I tried using it both before and after accept statements.

```
rename ${%o-6d%Y%m%d}00.grib1

directory ${PBD}/${%Y%m%d}/${SOURCE}/
accept .*grib.*

rename ${%Y%m%d}00.grib1
```

# Part 2

In a poll, it crashes.

```
Traceback (most recent call last):
  File "/local/home/sarra/sr3/sarracenia/instance.py", line 276, in <module>
    i.start()
  File "/local/home/sarra/sr3/sarracenia/instance.py", line 267, in start
    self.running_instance.run()
  File "/local/home/sarra/sr3/sarracenia/flow/__init__.py", line 591, in run
    self.gather()
  File "/local/home/sarra/sr3/sarracenia/flow/__init__.py", line 1160, in gather
    self._runCallbackPoll()
  File "/local/home/sarra/sr3/sarracenia/flow/__init__.py", line 386, in _runCallbackPoll
    new_incoming = plugin()
  File "/local/home/sarra/sr3/sarracenia/flowcb/poll/__init__.py", line 584, in poll
    msgs.extend(self.poll_directory(currentDir))
  File "/local/home/sarra/sr3/sarracenia/flowcb/poll/__init__.py", line 449, in poll_directory
    msgs.extend(self.poll_list_post(pdir, desclst, filelst))
  File "/local/home/sarra/sr3/sarracenia/flowcb/poll/__init__.py", line 552, in poll_list_post
    new_msgs = self.poll_file_post(desc, destDir, remote_file)
  File "/local/home/sarra/sr3/sarracenia/flowcb/poll/__init__.py", line 508, in poll_file_post
    msg = sarracenia.Message.fromFileInfo(post_relPath, self.o, desc)
  File "/local/home/sarra/sr3/sarracenia/__init__.py", line 742, in fromFileInfo
    msg['retrievePath'] = msg['new_retrievePath']
KeyError: 'new_retrievePath'
```

https://github.com/MetPX/sarracenia/blob/9cc7d8c616e77f3e6bb51e9994e8b1a93f2c500a/sarracenia/__init__.py#L750-L754

I'm not quite sure what's happening with retrievePath there. Maybe it's not necessary? Rename shouldn't change the relPath or retrievePath when the file is being posted

**Comment by petersilva** [comment]
@reidsunderland says this worked in a v2 watch.
