### ISSUE TITLE
New components: all-in-one Watch+Sender and Subscribe+Sender

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#1344]
I was curious if it was possible to combine a watch and sender into one config, with no broker.

I did get it working, but not without broker settings. I also ran into a few crashes due to other missing options that are normally defined in watch.py's default options.

I put the config in `~/.config/sr3/sender/config.conf` because I wasn't sure how to get sender.py's do method called in a Flow. Maybe it's possible using `flowMain`.

```
# watch + sender?

broker   amqp://bunnymaster@localhost/
exchange xs_bunnymaster

post_broker amqp://bunnymaster@localhost/
post_exchange xs_bunnymaster2

post_baseUrl sftp://localhost/

# watch config
callback gather.file
sleep    5s
path     /tmp/watchdir/
force_polling False
post_on_start True
blockSize 0

# send config
sendTo    sftp://localhost/
mirror False
directory /tmp/sender/

acceptUnmatched True
```

In this type of config, I doubt that we would ever want to consume messages from a broker, but it would be useful to optionally support posting to a broker (only the posting the files sent by the sender part, not the watch).

Here are the crashes I saw without certain options in the config:

```
[ERROR] 1012466 sarracenia.flow gather flowCallback plugin <bound method File.gather of <sarracenia.flowcb.gather.file.File object at 0x7fd23e7179d0>> crashed: 'Config' object has no attribute 'force_polling'

[ERROR] 1012519 sarracenia.flow gather flowCallback plugin <bound method File.gather of <sarracenia.flowcb.gather.file.File object at 0x7fa920217ac0>> crashed: 'Config' object has no attribute 'post_exchange'

[ERROR] 1012533 sarracenia.flow gather flowCallback plugin <bound method File.gather of <sarracenia.flowcb.gather.file.File object at 0x7fe7de67e950>> crashed: 'Config' object has no attribute 'post_on_start'

[ERROR] 1012596 sarracenia.flow gather flowCallback plugin <bound method File.gather of <sarracenia.flowcb.gather.file.File object at 0x7ff64f8024a0>> crashed: 'Config' object has no attribute 'blockSize'

[ERROR] 1012611 sarracenia updatePaths missing post_baseUrl setting
Traceback (most recent call last):
  File "/net/local/home/sunderlandr/sr3/sarracenia/instance.py", line 276, in <module>
    i.start()
  File "/net/local/home/sunderlandr/sr3/sarracenia/instance.py", line 267, in start
    self.running_instance.run()
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 600, in run
    self.filter()
  File "/net/local/home/sunderlandr/sr3/sarracenia/flow/__init__.py", line 1041, in filter
    url = self.o.variableExpansion(m['baseUrl'], m)
KeyError: 'baseUrl'

**Comment by petersilva** [comment]
This is very cool!

**Comment by petersilva** [comment]
I was thinking about this... and the downside is that the worklist is in memory so there is a bit of a risk if things crash and are restarted.  the worklist will be gone, and might have already gone through duplicate suppression, but not yet sent.

not a show stopper... but thing to be aware of.

**Comment by petersilva** [comment]
every student/person I ever had starting out with zero knowledge of sr3... when asked to create a configuration, expected this sort of thing to work... it's kind of a PoLA violation that it doesn't work.

**Comment by andreleblanc11** [comment]
Creating a new component for this might make sense.

**Comment by reidsunderland** [comment]
Another common use case that people seem to often want/need is a subscriber + sender combo.

i.e. download data from somewhere (e.g. Datamart) then send it somewhere else (typically cloud storage, like S3 or Azure).

The [cloud-publisher plugins](https://github.com/MetPX/sr3-examples/tree/main/cloud-publisher-s3) exist to do this, but it would be nice to have built in functionality that uses the transfer classes, so we can support sending to any destination.

If we ever get around to adding more components, this would be useful as well.

**Comment by reidsunderland** [comment]
This is usually requested by clients, but one case where it's useful to DI is for sending to AM clients. 

@kurt2x is running a subscriber on servers that downloads data, then sends it to an AM socket.

I wrote this subclass of the Am class to accomplish that:

```python
import os
import os.path
import logging
from sarracenia.flowcb.send.am import Am

logger = logging.getLogger(__name__)

class Am_from_subscriber(Am):
    """ Subclass of the default Am sender plugin.
        Adds an after_work.
        i.e. https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/send/am.py
    """
    def __init__(self, options):
        super().__init__(options)

    def after_work(self, worklist):
        """ After the file has been downloaded to the local node, send it via AM.
            In a sender config, do nothing.
        """
        if self.o.component == 'sender':
            logger.debug("nothing to do in a sender config ...")
            return
        else:
            good_msgs = []
            for msg in worklist.ok:
                if self.send(msg):
                    good_msgs.append(msg)
                else:
                    worklist.failed.append(msg)
                    try:
                        # need to delete the local file, otherwise it won't be downloaded/processed
                        # again because it already exists
                        os.remove(os.path.join(msg['new_dir'], msg['new_file']))
                    except Exception as e:
                        logger.error(f"failed to delete local file {e}", exc_info=True)
            worklist.ok = good_msgs
```

But that kind of thing only works when the sender is implemented as a plugin.

**Comment by reidsunderland** [comment]
Another way to accomplish the same goal (make it easy to watch+send or subscribe+send data) might be some kind of fake/mock local broker that's much easier to set up and configure. Like a queue on disk or similar.

Then we could continue to have separate watch/subscribe/senders, but users wouldn't have to deal with configuring an AMQP or MQTT broker for the intermediate subscribe/watch-->sender messages.
