### ISSUE TITLE
Sum header removal from body needed in v03 breaks pc_clean

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#160]
This code (in sr_message) is likely producing this issue:
```
               save_sum = self.headers[ "sum" ]
               del self.headers[ "sum" ]
               body = json.dumps(self.headers)
               self.headers[ "sum" ] = save_sum
               ok = self.publisher.publish(self.exchange+suffix, self.topic, body, None, self.message_ttl)
```

Here is a the section that failed in the flow test results:
```
                  | py infos   routing |
test 14 success: sr_shovel pclean_f90 (1373) should have the same number of watched items winnows' post	 (1379)
test 15 FAILURE: sr_shovel pclean_f92 (752) should have the same number of removed items winnows' post	 (1379)
test 16 success: 0 messages received that we don't know what happened.
test 17 success: count of truncated headers (1379) and subscribed messages (1379) should have about the same number of items
```
Those errors also seems relevant for that problem:
- In flow_check_errors_logged.txt
```
      1 sr_shovel_pclean_f92_01.log [ERROR] on_heartbeat something went wrong
      1 sr_shovel_pclean_f92_01.log [ERROR] Type: <class 'KeyError'>, Value: 'sum',  ...
```
- And in the corresponding shovel log, also got a bunch or warning like that:
```
2019-02-22 17:28:23,540 [WARNING] /citypage_weather/xml/AB/s0000829_e.xml not fully cleaned up
2019-02-22 17:28:23,540 [INFO] appended to retry list file {"atime": "20190222T220028.952750683", "from_cluster": "WXO", "mode": "664", "mtime": "20190222T222658.577731848", "parts": "1,29648,1,0,0", "source": "WXO", "to_clusters": "ALL", "pclean_f91": ".hlink", "pubTime": "20190222T222659.143776", "baseUrl": "http://localhost:8000", "relPath": "/citypage_weather/xml/AB/s0000829_e.xml", "integrity": {"method": "md5", "value": "rOfrczMB5qxqlF0F4f65iw=="}}
```

**Comment by benlapETS** [comment]
Running another test (with a `Maximum of the shovels is: 1028`), I noted that when the clean up failed the system log show this behavior:
```
2019-02-28 14:59:21,827 [DEBUG] consume AMQP or AMQPLIB is used
2019-02-28 14:59:21,836 [DEBUG] trim_headers
2019-02-28 14:59:21,836 [DEBUG] sr_config set_sumalgo d
2019-02-28 14:59:21,852 [DEBUG] notice 20190228T195757.115 http://localhost:8000 /bulletins/alphanumeric/20190228/SX/KWAL/19/SXAK50_KWAL_281957___76578
2019-02-28 14:59:21,853 [DEBUG] urlstr http://localhost:8000/bulletins/alphanumeric/20190228/SX/KWAL/19/SXAK50_KWAL_281957___76578
2019-02-28 14:59:21,853 [DEBUG] sr_consumer, path being matched: http://localhost:8000/bulletins/alphanumeric/20190228/SX/KWAL/19/SXAK50_KWAL_281957___76578:cvt_nws_bulletins-sr:KWAL:SX:3:Direct:20190228195756
2019-02-28 14:59:21,853 [DEBUG] isMatchingPattern: mask: ('.*', '/local/ben/sarra_devdocroot', None, re.compile('.*'), True, False, 0, None, '/')
2019-02-28 14:59:21,853 [DEBUG] isMatchingPattern: mask=('.*', '/local/ben/sarra_devdocroot', None, re.compile('.*'), True, False, 0, None, '/') strip=0
2019-02-28 14:59:21,853 [DEBUG] Received notice  20190228T195757.115 http://localhost:8000/bulletins/alphanumeric/20190228/SX/KWAL/19/SXAK50_KWAL_281957___76578
2019-02-28 14:59:21,853 [DEBUG] set_new strip=0, mirror=False flatten=/ pbd=None msg.relpath=/bulletins/alphanumeric/20190228/SX/KWAL/19/SXAK50_KWAL_281957___76578
2019-02-28 14:59:21,853 [DEBUG] set_new new_dir = /local/ben/sarra_devdocroot
2019-02-28 14:59:21,853 [INFO] msg_pclean_f92.py on_message
2019-02-28 14:59:21,853 [WARNING] /bulletins/alphanumeric/20190228/SX/KWAL/19/SXAK50_KWAL_281957___76578 not fully cleaned up
2019-02-28 14:59:21,864 [INFO] appended to retry list file {"atime": "20190228T195757.115", "filename": "msg_ddsr-WXO-DD3_a6a7037db0a04e9e56bdfc171ebf7548:cvt_nws_bulletins-sr:KWAL:SX:3:Direct:20190228195756", "from_cluster": "DDSR.CMC", "mtime": "20190228T195757.115", "parts": "1,246,1,0,0", "source": "WXO-DD", "sundew_extension": "cvt_nws_bulletins-sr:KWAL:SX:3:Direct:20190228195756", "to_clusters": "DDSR.CMC,DDI.CMC,CMC,SCIENCE,EDM", "pclean_f91": ".slink", "pubTime": "20190228T195757.115", "baseUrl": "http://localhost:8000", "relPath": "/bulletins/alphanumeric/20190228/SX/KWAL/19/SXAK50_KWAL_281957___76578", "integrity": {"method": "md5", "value": "GO4rU2BpP6Sl140ZynAP7A=="}}
2019-02-28 14:59:21,864 [DEBUG] --------------> ACK
2019-02-28 14:59:21,865 [DEBUG] --------------> 2
```
When it succeed we got that:
```
2019-02-28 14:59:57,092 [DEBUG] consume AMQP or AMQPLIB is used
2019-02-28 14:59:57,093 [DEBUG] trim_headers
2019-02-28 14:59:57,093 [DEBUG] sr_config set_sumalgo d
2019-02-28 14:59:57,093 [DEBUG] notice 20190228T195833.793 http://localhost:8000 /bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836
2019-02-28 14:59:57,093 [DEBUG] urlstr http://localhost:8000/bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836
2019-02-28 14:59:57,093 [DEBUG] sr_consumer, path being matched: http://localhost:8000/bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836:cvt_nws_bulletins-sr:KWAL:SR:3:Direct:20190228195832
2019-02-28 14:59:57,093 [DEBUG] isMatchingPattern: mask: ('.*', '/local/ben/sarra_devdocroot', None, re.compile('.*'), True, False, 0, None, '/')
2019-02-28 14:59:57,093 [DEBUG] isMatchingPattern: mask=('.*', '/local/ben/sarra_devdocroot', None, re.compile('.*'), True, False, 0, None, '/') strip=0
2019-02-28 14:59:57,093 [DEBUG] Received notice  20190228T195833.793 http://localhost:8000/bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836
2019-02-28 14:59:57,093 [DEBUG] set_new strip=0, mirror=False flatten=/ pbd=None msg.relpath=/bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836
2019-02-28 14:59:57,093 [DEBUG] set_new new_dir = /local/ben/sarra_devdocroot
2019-02-28 14:59:57,093 [INFO] msg_pclean_f92.py on_message
2019-02-28 14:59:57,093 [INFO] post_log notice=20190228T195833.793 http://localhost:8000 /bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836 headers={'atime': '20190228T195833.793', 'filename': 'msg_ddsr-WXO-DD3_8392b3830f0538c885698b8cdd4e4d05:cvt_nws_bulletins-sr:KWAL:SR:3:Direct:20190228195832', 'from_cluster': 'DDSR.CMC', 'mtime': '20190228T195833.793', 'parts': '1,151,1,0,0', 'source': 'WXO-DD', 'sundew_extension': 'cvt_nws_bulletins-sr:KWAL:SR:3:Direct:20190228195832', 'to_clusters': 'DDSR.CMC,DDI.CMC,CMC,SCIENCE,EDM', 'pubTime': '20190228T195833.793', 'baseUrl': 'http://localhost:8000', 'relPath': '/bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836', 'integrity': {'method': 'md5', 'value': 'JWsrVuzvq7haMrjZbEKImQ=='}, 'sum': 'd,256b2b56ecefabb85a32b8d96c428899', 'pclean_f92': '.slink'}
2019-02-28 14:59:57,094 [INFO] post_total: 0 messages posted: 0 msg/s, 0.0 bytes/s, lag: 0.0 s (RESET)
2019-02-28 14:59:57,094 [INFO] post_total:   1 messages posted:  0.01 msg/s, lag:   83 s
2019-02-28 14:59:57,094 [WARNING] total: Excessive lag! Messages posted a minute ago
2019-02-28 14:59:57,094 [DEBUG] publish AMQP is used
2019-02-28 14:59:57,094 [DEBUG] Published1: xs_tsource_clean_f92 v03.post.bulletins.alphanumeric.20190228.SR.KWAL.19
2019-02-28 14:59:57,095 [DEBUG] Published2: '20190228T195833.793 http://localhost:8000 /bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836' atime=20190228T195833.793 baseUrl=http://localhost:8000 filename=msg_ddsr-WXO-DD3_8392b3830f0538c885698b8cdd4e4d05:cvt_nws_bulletins-sr:KWAL:SR:3:Direct:20190228195832 from_cluster=DDSR.CMC integrity={'method': 'md5', 'value': 'JWsrVuzvq7haMrjZbEKImQ=='} mtime=20190228T195833.793 parts=1,151,1,0,0 pclean_f92=.slink pubTime=20190228T195833.793 relPath=/bulletins/alphanumeric/20190228/SR/KWAL/19/SRWA20_KWAL_281958___36836 source=WXO-DD sum=d,256b2b56ecefabb85a32b8d96c428899 sundew_extension=cvt_nws_bulletins-sr:KWAL:SR:3:Direct:20190228195832 to_clusters=DDSR.CMC,DDI.CMC,CMC,SCIENCE,EDM
2019-02-28 14:59:57,095 [DEBUG] --------------> ACK
2019-02-28 14:59:57,095 [DEBUG] --------------> 188
```
So a fail concludes with adding to retry list and a success concludes with a publish to the exchange. This test showed that in pclean f92:
- 1022 msgs were received
- 708 msgs were added to retry list (failed)
- 314 msgs were published

Compare to other pclean:
- 1022 msgs were received
- 2138 (f90) and 2059 (f91) were appended to retry list
- 1022 msgs were published

Then, it looks like something is wrong with the retry list in f92. My other question is why is there so many retry in the flow test ? this is a test that is mostly run locally it is a bit odd that so many msg get lost and needs to retry

**Comment by petersilva** [comment]
the clean routines are specifically engineered to exercise the retry logic.  I'm not sure how it is done, but the point is to make sure that things get queued for retry, and then recovered from the retry queue and completed.  That there is a large number of retries is completely intentional.

**Comment by benlapETS** [comment]
How are implemented those clean routines ? where ? from the pclean .conf files ?

**Comment by petersilva** [comment]
yeah, that's worthwhile. Michel is the only one who ever understood them.  It would be good for someone else to know them.

**Comment by benlapETS** [comment]
The consume-2-retry or consume-2-publish routines can be represented by this sequence:
![consumer](https://user-images.githubusercontent.com/11091581/53755595-e29c2580-3e84-11e9-9f2e-c955e60712ff.png)

**Comment by benlapETS** [comment]
And the problem was located here:
```
2019-02-28 14:59:24,477 [DEBUG] consume AMQP or AMQPLIB is used
2019-02-28 14:59:27,043 [DEBUG] __on_heartbeat__
2019-02-28 14:59:27,043 [INFO] heartbeat. Sarracenia version is: 2.19.02b3 

2019-02-28 14:59:27,043 [INFO] hb_memory cpu_times user=0.27 system=0.02 elapse=17185107.6
2019-02-28 14:59:27,043 [INFO] hb_memory current usage: 48.1 MiB, accumulating count (0 or 4 of 100 so far) before setting threshold
2019-02-28 14:59:27,043 [INFO] hb_pulse message_count 4 publish_count 0 
2019-02-28 14:59:27,047 [DEBUG] hb_pulse no messages receive but still connected.
2019-02-28 14:59:27,047 [INFO] hb_retry on_heartbeat
2019-02-28 14:59:27,047 [INFO] sr_retry on_heartbeat
2019-02-28 14:59:27,065 [ERROR] sr_retry/on_heartbeat: something went wrong
2019-02-28 14:59:27,065 [DEBUG] General exception: 
Traceback (most recent call last):
  File "/local/ben/git/sarracenia/sarra/sr_retry.py", line 400, in on_heartbeat
    if self.in_cache(message): continue
  File "/local/ben/git/sarracenia/sarra/sr_retry.py", line 203, in in_cache
    sumstr  = message.properties['application_headers']['sum']
KeyError: 'sum'
2019-02-28 14:59:27,079 [INFO] No retry in list
2019-02-28 14:59:27,080 [INFO] sr_retry on_heartbeat elapse 0.032543
```
Where sr_retry was failing with key error on the raw message because sum does not exist in v03.

**Comment by benlapETS** [comment]
Here is how looks this retry handling routine:
![image](https://user-images.githubusercontent.com/11091581/53762892-50e9e380-3e97-11e9-9925-696e467fd9f3.png)

**Comment by petersilva** [comment]
I'm a little unsure... is this another way it fails when using v03 after a while, or is this still fixed by what you did last week?

**Comment by benlapETS** [comment]
It is still fixed, just wanted to document some important routine through this issue

**Comment by benlapETS** [comment]
I think I see the design flaw here. There is a duplication of code because we gives the responsability of serializing and deserializing msg to sr_retry using the raw_msg directly. sr_message should encapsulate the raw_msg it represents and it should handles the ser/deser process which would be called by whatever class needs to recover/save messages, so we would nt have to reparse raw_msg everytime. It would also be a nice way to save any versions we want our sr_message to support...
