### ISSUE TITLE
issue with new amqp library

### ISSUE THREAD

**Issue by habilinour** [MetPX/sarracenia#162]
Thew new library is not compatible with Ubuntu 16.04, so we still need amqlib to run sarra on Ubuntu16.04.

**Comment by habilinour** [comment]
Some log  showing  the error on Ubuntu 16.04

2019-02-27 05:48:23,147 [ERROR] Traceback (most recent call last):
2019-02-27 05:48:23,148 [ERROR]   File "/usr/lib/python3.5/logging/__init__.py", line 983, in emit
2019-02-27 05:48:23,148 [ERROR]     stream.write(self.terminator)
2019-02-27 05:48:23,148 [ERROR] OSError: [Errno 5] Input/output error
2019-02-27 05:48:23,148 [ERROR] Call stack:
2019-02-27 05:48:23,148 [ERROR]   File "/usr/bin/sr_watch", line 9, in <module>
2019-02-27 05:48:23,148 [ERROR]     load_entry_point('metpx-sarracenia==2.19.2b2', 'console_scripts', 'sr_watch')()
2019-02-27 05:48:23,148 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_watch.py", line 65, in main
2019-02-27 05:48:23,148 [ERROR]     watch.exec_action(action,old)
2019-02-27 05:48:23,148 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 301, in exec_action
2019-02-27 05:48:23,148 [ERROR]     elif action == 'start'      : self.start_parent()
2019-02-27 05:48:23,148 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 785, in start_parent
2019-02-27 05:48:23,148 [ERROR]     self.start()
2019-02-27 05:48:23,148 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_post.py", line 1485, in start
2019-02-27 05:48:23,148 [ERROR]     self.run()
2019-02-27 05:48:23,149 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_post.py", line 1436, in run
2019-02-27 05:48:23,149 [ERROR]     self.connect()
2019-02-27 05:48:23,149 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_post.py", line 191, in connect
2019-02-27 05:48:23,154 [ERROR]     if not self.post_hc.connect():
2019-02-27 05:48:23,154 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_amqp.py", line 119, in connect
2019-02-27 05:48:23,154 [ERROR]     virtual_host=self.vhost, ssl=self.ssl)
2019-02-27 05:48:23,154 [ERROR]   File "/usr/lib/python3/dist-packages/amqp/connection.py", line 183, in __init__
2019-02-27 05:48:23,154 [ERROR]     return self._x_open(virtual_host)
2019-02-27 05:48:23,154 [ERROR]   File "/usr/lib/python3/dist-packages/amqp/connection.py", line 628, in _x_open
2019-02-27 05:48:23,154 [ERROR]     (10, 41),    # Connection.open_ok
2019-02-27 05:48:23,154 [ERROR]   File "/usr/lib/python3/dist-packages/amqp/abstract_channel.py", line 69, in wait
2019-02-27 05:48:23,154 [ERROR]     return self.dispatch_method(method_sig, args, content)
2019-02-27 05:48:23,155 [ERROR]   File "/usr/lib/python3/dist-packages/amqp/abstract_channel.py", line 87, in dispatch_method
2019-02-27 05:48:23,155 [ERROR]     return amqp_method(self, args)
2019-02-27 05:48:23,155 [ERROR]   File "/usr/lib/python3/dist-packages/amqp/connection.py", line 641, in _open_ok
2019-02-27 05:48:23,155 [ERROR]     AMQP_LOGGER.debug('Open OK!')
2019-02-27 05:48:23,155 [ERROR] Message: 'Open OK!'
2019-02-27 05:48:23,155 [ERROR] Arguments: ()
2019-02-27 05:48:23,155 [ERROR] AMQP Sender cannot connect to: localhost
2019-02-27 05:48:23,155 [ERROR] Type=<class 'AttributeError'>, Value='Connection' object has no attribute 'connect'

**Comment by benlapETS** [comment]
I reproduced it with amqp 1.3.3 and I just found the one liner which will likely fix this issue. Until this goes to the next release you may use option `use_amqplib`
