### ISSUE TITLE
sr_watch crash with inotify error on long runs

### ISSUE THREAD

**Issue by benlapETS** [MetPX/sarracenia#204]
I got those error today which are relevant to mention:
```
sr_watch_f40_01.log:2019-05-14 00:15:54,390 [ERROR] Traceback (most recent call last): sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,390 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/bin/sr_watch", line 11, in <module> sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,390 [ERROR] load_entry_point('metpx-sarracenia', 'console_scripts', 'sr_watch')() sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,390 [ERROR]   File "/local/ben/git/sarracenia/sarra/sr_watch.py", line 65, in main sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,432 [ERROR] watch.exec_action(action,old) sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,432 [ERROR]   File "/local/ben/git/sarracenia/sarra/sr_instances.py", line 308, in exec_action sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,439 [ERROR] elif action == 'start'      : self.start_parent() sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,439 [ERROR]   File "/local/ben/git/sarracenia/sarra/sr_instances.py", line 792, in start_parent sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,439 [ERROR] self.start() sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,440 [ERROR]   File "/local/ben/git/sarracenia/sarra/sr_post.py", line 1463, in start sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,553 [ERROR] self.run() sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,553 [ERROR]   File "/local/ben/git/sarracenia/sarra/sr_post.py", line 1437, in run sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,554 [ERROR] self.watch_dir(d) sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,554 [ERROR]   File "/local/ben/git/sarracenia/sarra/sr_post.py", line 1251, in watch_dir sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,555 [ERROR] self.observer.start() sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,555 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/lib/python3.7/site-packages/watchdog/observers/api.py", line 255, in start sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,595 [ERROR] emitter.start() sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,595 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/lib/python3.7/site-packages/watchdog/utils/__init__.py", line 110, in start sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,607 [ERROR] self.on_thread_start() sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,607 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/lib/python3.7/site-packages/watchdog/observers/inotify.py", line 121, in on_thread_start sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,648 [ERROR] self._inotify = InotifyBuffer(path, self.watch.is_recursive) sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,648 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/lib/python3.7/site-packages/watchdog/observers/inotify_buffer.py", line 35, in __init__ sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,651 [ERROR] self._inotify = Inotify(path, recursive) sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,651 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 199, in __init__ sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,653 [ERROR] self._add_dir_watch(path, recursive, event_mask) sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,653 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 387, in _add_dir_watch sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,654 [ERROR] self._add_watch(full_path, mask) sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,654 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 401, in _add_watch sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,654 [ERROR] Inotify._raise_error() sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,654 [ERROR]   File "/local/ben/anaconda3/envs/base_sarra/lib/python3.7/site-packages/watchdog/observers/inotify_c.py", line 413, in _raise_error sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,654 [ERROR] raise OSError("inotify watch limit reached") sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,654 [ERROR] OSError sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,654 [ERROR] : sr_config/write line#85 17614
sr_watch_f40_01.log-2019-05-14 00:15:54,654 [ERROR] inotify watch limit reached sr_config/write line#85 17614
```
Those happens in long running tests with the risk of getting into a peak of notifications which overpass inotify limits. It is mention on those posts ([stackexchange](https://unix.stackexchange.com/questions/13751/kernel-inotify-watch-limit-reached) and [askubuntu](https://askubuntu.com/questions/154255/how-can-i-tell-if-i-am-out-of-inotify-watches)) the default limit is admitted to be quite low. This other [link](https://stackoverflow.com/questions/13758877/how-do-i-find-out-what-inotify-watches-have-been-registered) may be useful for sysctl cmds.

But my questions are: 
- Is it normal to accumulate 377731 event during the process and how many did it take to blow up sr_watch. 
- Was the observer thread accumulating inotify event without unscheduling it, or did it blew up because of a peak of notifications ?

I managed to count events with those cmd (with debug switch on):
- Total: `grep -c -o in-event flowsetup_f00.log*` 
- Count by blocks: `grep -1 -o in-event flowsetup_f00.log* | uniq -c | grep -v "1 \-\-" | less`

**Comment by benlapETS** [comment]
Note (May 14): This issue blocked me from completing #182 because I wanted to document the inotify problem.

**Comment by benlapETS** [comment]
This is how I managed to get all the count obtained by plugins:
```
# for i in file_total msg_total post_total; do for j in sr_*.log*; do grep -H "$i" $j | grep -v DEBUG | tail -1 >> test.txt; done; done;
# cat test.txt | sort | less
```

**Comment by benlapETS** [comment]
Added documentation how to increase watch limit and linked that issue as a reference.
