### ISSUE TITLE
Logging errors when run in debug mode

### ISSUE THREAD

**Issue by racetted** [MetPX/sarracenia#249]
Testing done on `ppc rhel 7.5`, with sarracenia version `2.19.04b2`. 

Starting with debug will yeild various error messages. Sample: 

```
2019-08-27 12:18:53,918 [INFO] sr_subscribe mirror-ss2-from-hall3 start
2019-08-27 12:18:53,918 [INFO] log settings start for sr_subscribe (version: 2.19.04b2):
2019-08-27 12:18:53,918 [INFO]  inflight=.tmp events=create|delete|link|modify use_pika=False topic_prefix=v02.post
2019-08-27 12:18:53,918 [INFO]  inflight=.tmp events=create|delete|link|modify use_amqplib=False topic_prefix=v02.post
2019-08-27 12:18:53,918 [INFO]  suppress_duplicates=False basis=path retry_mode=True retry_ttl=900000ms
2019-08-27 12:18:53,919 [INFO]  expire=900000ms reset=False message_ttl=None prefetch=25 accept_unmatch=False delete=False
2019-08-27 12:18:53,919 [INFO]  heartbeat=300 sanity_log_dead=450 default_mode=645 default_mode_dir=775 default_mode_log=644 discard=False durable=True
2019-08-27 12:18:53,919 [INFO]  post_on_start=True preserve_mode=False preserve_time=True realpath_post=False base_dir=None follow_symlinks=False
2019-08-27 12:18:53,919 [INFO]  mirror=True flatten=/ realpath_post=False strip=7 base_dir=None report_back=False
2019-08-27 12:18:53,919 [INFO]  post_base_dir=None post_base_url=smco507@ss3sitenfsx: post_topic_prefix=v02.post post_version=v02 sum=d blocksize=0
2019-08-27 12:18:53,919 [INFO]  Plugins configured:
2019-08-27 12:18:53,919 [INFO]      do_download: CP_DOWNLOAD
2019-08-27 12:18:53,919 [INFO]      do_get     :
2019-08-27 12:18:53,919 [INFO]      on_message: Msg_Log
2019-08-27 12:18:53,919 [INFO]      on_data:
2019-08-27 12:18:53,920 [INFO]      on_part:
2019-08-27 12:18:53,920 [INFO]      on_file: File_Log File_Age
2019-08-27 12:18:53,920 [INFO]      on_post: Post_Log
2019-08-27 12:18:53,920 [INFO]      on_heartbeat: Hb_Log Hb_Memory Hb_Pulse RETRY
2019-08-27 12:18:53,920 [INFO]      on_report:
2019-08-27 12:18:53,920 [INFO]      on_start:
2019-08-27 12:18:53,920 [INFO]      on_stop:
2019-08-27 12:18:53,920 [INFO] log_settings end.
2019-08-27 12:18:53,920 [INFO] sr_subscribe run
2019-08-27 12:18:53,921 [DEBUG] sr_consumer __init__
2019-08-27 12:18:53,921 [DEBUG] sr_retry __init__
2019-08-27 12:18:53,921 [DEBUG] sr_consumer isReporting
2019-08-27 12:18:53,921 [DEBUG] sr_consumer build_broker
2019-08-27 12:18:53,921 [INFO] AMQP  broker(ddsr.science.gc.ca) user(MSC-SCI-CMC) vhost(/)
2019-08-27 12:18:53,921 [DEBUG] Connecting ddsr.science.gc.ca MSC-SCI-CMC (ssl True)
2019-08-27 12:18:53,921 [DEBUG] amqps://MSC-SCI-CMC:<pw>@ddsr.science.gc.ca:5671/ ssl=True
2019-08-27 12:18:53,922 [INFO] Using amqp module (AMQP 0-9-1)
2019-08-27 12:18:53,953 [ERROR] --- Logging error ---
2019-08-27 12:18:53,953 [ERROR] Traceback (most recent call last):
2019-08-27 12:18:53,953 [ERROR]   File "/usr/lib64/python3.6/logging/__init__.py", line 998, in emit
2019-08-27 12:18:53,953 [ERROR]     self.flush()
2019-08-27 12:18:53,954 [ERROR]   File "/usr/lib64/python3.6/logging/__init__.py", line 978, in flush
2019-08-27 12:18:53,954 [ERROR]     self.stream.flush()
2019-08-27 12:18:53,954 [ERROR] BrokenPipeError: [Errno 32] Broken pipe
2019-08-27 12:18:53,954 [ERROR] Call stack:
2019-08-27 12:18:53,955 [ERROR]   File "/usr/local/bin/sr_subscribe", line 10, in <module>
2019-08-27 12:18:53,955 [ERROR]     sys.exit(main())
2019-08-27 12:18:53,955 [ERROR]   File "/usr/local/lib/python3.6/site-packages/sarra/sr_subscribe.py", line 2219, in main
2019-08-27 12:18:53,956 [ERROR]     subscribe.exec_action(action,old)
2019-08-27 12:18:53,956 [ERROR]   File "/usr/local/lib/python3.6/site-packages/sarra/sr_instances.py", line 301, in exec_action
2019-08-27 12:18:53,956 [ERROR]     elif action == 'start'      : self.start_parent()
2019-08-27 12:18:53,956 [ERROR]   File "/usr/local/lib/python3.6/site-packages/sarra/sr_instances.py", line 785, in start_parent
2019-08-27 12:18:53,956 [ERROR]     self.start()
2019-08-27 12:18:53,956 [ERROR]   File "/usr/local/lib/python3.6/site-packages/sarra/sr_subscribe.py", line 1949, in start
2019-08-27 12:18:53,956 [ERROR]     self.run()
2019-08-27 12:18:53,956 [ERROR]   File "/usr/local/lib/python3.6/site-packages/sarra/sr_subscribe.py", line 1721, in run
2019-08-27 12:18:53,956 [ERROR]     self.connect()
```
There is more trace available.

**Comment by petersilva** [comment]
#240 fix will likely fix this as well... perhaps git clone the branch in on a machine running this Os and see if issue240_2 branch fixes this.

**Comment by benlapETS** [comment]
Note1: This is how to reproduce activate debug level and file rotation at the same time.

**Comment by benlapETS** [comment]
I will try to pinpoint what in the code triggered that problem to build test case to ensure this does never come back.

**Comment by benlapETS** [comment]
Unfortunately (from the testing perspective, but fortunately from the dev's) I couldn't reproduce on master so I won't be able to implement test for that. In fact, I think it would be time consuming and worthless as it is now resolved and it would take a combination of stepback to reproduce that problem.
