### ISSUE TITLE
self.flush() not found error message...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#252]
```
2019-08-20 08:03:14,829 [ERROR] --- Logging error ---
2019-08-20 08:03:14,829 [ERROR] Traceback (most recent call last):
2019-08-20 08:03:14,829 [ERROR]   File "/usr/lib/python3.6/logging/__init__.py", line 998, in emit
2019-08-20 08:03:14,829 [ERROR]     self.flush()
2019-08-20 08:03:14,829 [ERROR]   File "/usr/lib/python3.6/logging/__init__.py", line 978, in flush
2019-08-20 08:03:14,829 [ERROR]     self.stream.flush()
2019-08-20 08:03:14,829 [ERROR] BrokenPipeError: [Errno 32] Broken pipe
2019-08-20 08:03:14,829 [ERROR] Call stack:
2019-08-20 08:03:14,830 [ERROR]   File "/usr/bin/sr_subscribe", line 11, in <module>
2019-08-20 08:03:14,830 [ERROR]     load_entry_point('metpx-sarracenia==2.19.4b2', 'console_scripts', 'sr_subscribe')()
2019-08-20 08:03:14,830 [ERROR]   File "/home/peter/src/sarracenia/sarra/sr_subscribe.py", line 2195, in main
2019-08-20 08:03:14,830 [ERROR]     subscribe.exec_action(action,old)
2019-08-20 08:03:14,830 [ERROR]   File "/home/peter/src/sarracenia/sarra/sr_instances.py", line 301, in exec_action
2019-08-20 08:03:14,830 [ERROR]     elif action == 'start'      : self.start_parent()
2019-08-20 08:03:14,830 [ERROR]   File "/home/peter/src/sarracenia/sarra/sr_instances.py", line 778, in start_parent
2019-08-20 08:03:14,830 [ERROR]     self.start()
2019-08-20 08:03:14,831 [ERROR]   File "/home/peter/src/sarracenia/sarra/sr_subscribe.py", line 1925, in start
2019-08-20 08:03:14,831 [ERROR]     self.run()
2019-08-20 08:03:14,831 [ERROR]   File "/home/peter/src/sarracenia/sarra/sr_subscribe.py", line 1695, in run
2019-08-20 08:03:14,831 [ERROR]     self.connect()
2019-
```

it goes on with a full stack trace... Guess: a dummy logger is used at the beginning, and it isn't getting overridden.   This is probably related to the root cause of the ssh not exiting thing, because the dummy logger likely doesn't re-direct file descriptors. except the message is in the log... hmm... puzzling..

This is was produced by running sr_subscribe start cclean_f91 and looking at the log...

**Comment by petersilva** [comment]
@benlapETS I expect the work you have done to fix the logging & re-direction will fix this.
After #240 is done, probably check this, and will not be able to reproduce anymore... easy win.

**Comment by petersilva** [comment]
ugh... I can't reproduce it now, even on the old version... so hard to tell if it is fixed if we don't have that.
hmm...

**Comment by benlapETS** [comment]
I identified how to reprodruce effectively, everything is documented in #249
