### ISSUE TITLE
log error flush stack trace printed for every message retry.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#254]
2019-09-04 15:08:29,592 [ERROR] --- Logging error ---
2019-09-04 15:08:29,593 [ERROR] Traceback (most recent call last):
2019-09-04 15:08:29,593 [ERROR]   File "/usr/lib/python3.5/logging/__init__.py", line 984, in emit
2019-09-04 15:08:29,593 [ERROR]     self.flush()
2019-09-04 15:08:29,593 [ERROR]   File "/usr/lib/python3.5/logging/__init__.py", line 964, in flush
2019-09-04 15:08:29,593 [ERROR]     self.stream.flush()
2019-09-04 15:08:29,594 [ERROR] BrokenPipeError: [Errno 32] Broken pipe
2019-09-04 15:08:29,594 [ERROR] Call stack:
2019-09-04 15:08:29,598 [ERROR]   File "/usr/bin/sr_sender", line 9, in <module>
2019-09-04 15:08:29,598 [ERROR]     load_entry_point('metpx-sarracenia==2.19.4b2', 'console_scripts', 'sr_sender')()
2019-09-04 15:08:29,598 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sender.py", line 348, in main
2019-09-04 15:08:29,598 [ERROR]     sender.exec_action(action,old)
2019-09-04 15:08:29,598 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 301, in exec_action
2019-09-04 15:08:29,598 [ERROR]     elif action == 'start'      : self.start_parent()
2019-09-04 15:08:29,599 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 778, in start_parent
2019-09-04 15:08:29,599 [ERROR]     self.start()
2019-09-04 15:08:29,599 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 1925, in start
2019-09-04 15:08:29,599 [ERROR]     self.run()
2019-09-04 15:08:29,599 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 1755, in run
2019-09-04 15:08:29,600 [ERROR]     ok = self.process_message()
2019-09-04 15:08:29,600 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 938, in process_message
2019-09-04 15:08:29,600 [ERROR]     ok = self.__do_tasks__()
2019-09-04 15:08:29,600 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 421, in __do_tasks__
2019-09-04 15:08:29,600 [ERROR]     if not plugin(self): return False
2019-09-04 15:08:29,601 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sender.py", line 311, in doit_send
2019-09-04 15:08:29,601 [ERROR]     ok = self.__do_send__()
2019-09-04 15:08:29,601 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sender.py", line 202, in __do_send__
2019-09-04 15:08:29,601 [ERROR]     ok = self.sftp_link.send(self)
2019-09-04 15:08:29,601 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_util.py", line 595, in send
2019-09-04 15:08:29,601 [ERROR]     ok = proto.connect()
2019-09-04 15:08:29,602 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sftp.py", line 201, in connect
2019-09-04 15:08:29,602 [ERROR]     if not self.credentials() : return False
2019-09-04 15:08:29,602 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sftp.py", line 254, in credentials
2019-09-04 15:08:29,602 [ERROR]     ok, details = self.parent.credentials.get(self.destination)
2019-09-04 15:08:29,602 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_credentials.py", line 90, in get
2019-09-04 15:08:29,603 [ERROR]     self.logger.debug("sr_credentials get %s" % urlstr)
2019-09-04 15:08:29,603 [ERROR] Message: 'sr_credentials get sftp://px@hostname'
2019-09-04 15:08:29,603 [ERROR] Arguments: ()
2019-09-04 15:08:29,603 [ERROR] --- Logging error ---
2019-09-04 15:08:29,604 [ERROR] Traceback (most recent call last):
2019-09-04 15:08:29,604 [ERROR]   File "/usr/lib/python3.5/logging/__init__.py", line 984, in emit
2019-09-04 15:08:29,604 [ERROR]     self.flush()
2019-09-04 15:08:29,604 [ERROR]   File "/usr/lib/python3.5/logging/__init__.py", line 964, in flush
2019-09-04 15:08:29,604 [ERROR]     self.stream.flush()
2019-09-04 15:08:29,604 [ERROR] BrokenPipeError: [Errno 32] Broken pipe
2019-09-04 15:08:29,605 [ERROR] Call stack:
2019-09-04 15:08:29,605 [ERROR]   File "/usr/bin/sr_sender", line 9, in <module>
2019-09-04 15:08:29,605 [ERROR]     load_entry_point('metpx-sarracenia==2.19.4b2', 'console_scripts', 'sr_sender')()
2019-09-04 15:08:29,605 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sender.py", line 348, in main
2019-09-04 15:08:29,606 [ERROR]     sender.exec_action(action,old)
2019-09-04 15:08:29,606 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 301, in exec_action
2019-09-04 15:08:29,606 [ERROR]     elif action == 'start'      : self.start_parent()
2019-09-04 15:08:29,606 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 778, in start_parent
2019-09-04 15:08:29,606 [ERROR]     self.start()
2019-09-04 15:08:29,607 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 1925, in start
2019-09-04 15:08:29,607 [ERROR]     self.run()
2019-09-04 15:08:29,607 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 1755, in run
2019-09-04 15:08:29,607 [ERROR]     ok = self.process_message()
2019-09-04 15:08:29,607 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 938, in process_message
2019-09-04 15:08:29,608 [ERROR]     ok = self.__do_tasks__()
2019-09-04 15:08:29,608 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 421, in __do_tasks__
2019-09-04 15:08:29,608 [ERROR]     if not plugin(self): return False
2019-09-04 15:08:29,608 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sender.py", line 311, in doit_send
2019-09-04 15:08:29,608 [ERROR]     ok = self.__do_send__()
2019-09-04 15:08:29,608 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sender.py", line 202, in __do_send__
2019-09-04 15:08:29,609 [ERROR]     ok = self.sftp_link.send(self)
2019-09-04 15:08:29,609 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_util.py", line 595, in send
2019-09-04 15:08:29,609 [ERROR]     ok = proto.connect()
2019-09-04 15:08:29,609 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sftp.py", line 201, in connect
2019-09-04 15:08:29,609 [ERROR]     if not self.credentials() : return False
2019-09-04 15:08:29,610 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_sftp.py", line 254, in credentials
2019-09-04 15:08:29,610 [ERROR]     ok, details = self.parent.credentials.get(self.destination)
2019-09-04 15:08:29,610 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_credentials.py", line 94, in get
2019-09-04 15:08:29,610 [ERROR]     if self.has(urlstr) :
2019-09-04 15:08:29,610 [ERROR]   File "/usr/lib/python3/dist-packages/sarra/sr_credentials.py", line 118, in has
2019-09-04 15:08:29,610 [ERROR]     self.logger.debug("sr_credentials has %s" % urlstr)
2019-09-04 15:08:29,611 [ERROR] Message: 'sr_credentials has sftp://px@hostname'
2019-09-04 15:08:29,611 [ERROR] Arguments: ()

**Comment by petersilva** [comment]
@benlapETS likely the same root cause as #240... need to to test after merge.

**Comment by benlapETS** [comment]
were we at the debug level here ?
