### ISSUE TITLE
Poll process dies when it could not connect to the remote server

### ISSUE THREAD

**Issue by habilinour** [MetPX/sarracenia#304]
The poll process dies if it cannot connect to the remote server. Here is the log

2020-02-06 23:57:34,581 [INFO] sr_poll nrcan_sentinel startup
2020-02-06 23:57:34,582 [INFO] log settings start for sr_poll (version: 2.20.02b1):
2020-02-06 23:57:34,582 [INFO] 	inflight=unspecified events=create|delete|link|modify use_pika=False topic_prefix=v02.post
2020-02-06 23:57:34,582 [INFO] 	inflight=unspecified events=create|delete|link|modify use_amqplib=False topic_prefix=v02.post
2020-02-06 23:57:34,582 [INFO] 	suppress_duplicates=1200 basis=path retry_mode=True retry_ttl=Nonems tls_rigour=normal
2020-02-06 23:57:34,582 [INFO] 	expire=86400000ms reset=False message_ttl=None prefetch=25 accept_unmatch=False delete=False poll_without_vip=True
2020-02-06 23:57:34,582 [INFO] 	heartbeat=300 sanity_log_dead=450 default_mode=400 default_mode_dir=775 default_mode_log=600 discard=False durable=True
2020-02-06 23:57:34,583 [INFO] 	post_on_start=True preserve_mode=True preserve_time=True realpath_post=False base_dir=None follow_symlinks=False
2020-02-06 23:57:34,583 [INFO] 	mirror=False flatten=/ realpath_post=False strip=0 base_dir=None report_back=True log_reject=False
2020-02-06 23:57:34,583 [INFO] 	post_base_dir=None post_base_url=ftp://user@server post_topic_prefix=v02.post post_version=v02 sum=z,d blocksize=209715200 
2020-02-06 23:57:34,583 [INFO] 	Plugins configured:
2020-02-06 23:57:34,583 [INFO] 		on_line: Line_Mode establish the 
2020-02-06 23:57:34,583 [INFO] 		on_html_page: Html_parser 
2020-02-06 23:57:34,583 [INFO] 		do_poll: 
2020-02-06 23:57:34,583 [INFO] 		on_message: 
2020-02-06 23:57:34,583 [INFO] 		on_data: 
2020-02-06 23:57:34,583 [INFO] 		on_part: 
2020-02-06 23:57:34,583 [INFO] 		on_file: File_Log 
2020-02-06 23:57:34,583 [INFO] 		on_post: Post_Log 
2020-02-06 23:57:34,584 [INFO] 		on_heartbeat: Hb_Log Hb_Memory Hb_Pulse 
2020-02-06 23:57:34,584 [INFO] 		on_report: 
2020-02-06 23:57:34,584 [INFO] 		on_start: 
2020-02-06 23:57:34,584 [INFO] 		on_stop: 
2020-02-06 23:57:34,584 [INFO] log_settings end.
2020-02-06 23:57:34,585 [INFO] Using amqp module (AMQP 0-9-1)
2020-02-06 23:57:34,605 [INFO] Output AMQP broker(localhost) user(NRCAN) vhost(/)
2020-02-06 23:57:34,606 [INFO] Output AMQP exchange(xs_NRCAN)
2020-02-06 23:57:34,608 [ERROR] could not declare exchange xs_NRCAN (NRCAN@localhost): Exchange.declare: (403) ACCESS_REFUSED - access to exchange 'xs_NRCAN' in vhost '/' refused for user 'NRCAN'
2020-02-06 23:57:34,617 [INFO] sr_poll is sleeping without vip=142.135.12.137
2020-02-06 23:57:46,630 [ERROR] sr_poll/post_new_url: unable to connect to ftp://user@server
2020-02-06 23:57:46,630 [ERROR] Sleeping 30 secs and retry
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarra/sr_poll.py", line 684, in <module>
    main()
  File "/usr/lib/python3/dist-packages/sarra/sr_poll.py", line 675, in main
    poll.exec_action(action,old)
  File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 301, in exec_action
    elif action == 'start'      : self.start_parent()
  File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 761, in start_parent
    self.start()
  File "/usr/lib/python3/dist-packages/sarra/sr_post.py", line 1475, in start
    self.run()
  File "/usr/lib/python3/dist-packages/sarra/sr_poll.py", line 664, in run
    time.sleep(self.sleep)
  File "/usr/lib/python3/dist-packages/sarra/sr_util.py", line 65, in alarm_raise
    raise TimeoutException("signal alarm timed out")
sr_util.TimeoutException: signal alarm timed out

**Comment by petersilva** [comment]
63b16e1d48444ad4d18f16bff48f4129a498455c wraps that code in a try/except, attempts resolution.

**Comment by petersilva** [comment]
@habilinour also please confirm whether this is fixed in 2.20.02b3

**Comment by habilinour** [comment]
The new release seems to fix the issue. The process kept running and logging the following error 

2020-02-26 15:16:51,525 [DEBUG] poll nrcan is waking up
2020-02-26 15:16:51,525 [DEBUG] sr_ftp __init__
2020-02-26 15:16:51,525 [DEBUG] sr_ftp init
2020-02-26 15:16:51,526 [DEBUG] iotime 90
2020-02-26 15:16:51,526 [DEBUG] sr_ftp init
2020-02-26 15:16:51,526 [DEBUG] iotime 90
2020-02-26 15:16:51,526 [DEBUG] sr_ftp connect ftp://shahid.khurshid@ec.gc.ca@ftp.neodf.nrcan.gc.ca
2020-02-26 15:16:51,526 [DEBUG] sr_ftp credentials ftp://user@server
2020-02-26 15:16:51,526 [DEBUG] sr_credentials has ftp://user@server
2020-02-26 15:17:03,553 [ERROR] sr_poll/post_new_url: unable to connect to ftp://user@server
2020-02-26 15:17:03,553 [DEBUG] Exception details: 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarra/sr_ftp.py", line 190, in connect
    ftp.connect(self.host,self.port,timeout=expire)
  File "/usr/lib/python3.5/ftplib.py", line 156, in connect
    self.welcome = self.getresp()
  File "/usr/lib/python3.5/ftplib.py", line 235, in getresp
    resp = self.getmultiline()
  File "/usr/lib/python3.5/ftplib.py", line 221, in getmultiline
    line = self.getline()
  File "/usr/lib/python3.5/ftplib.py", line 203, in getline
    line = self.file.readline(self.maxline + 1)
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarra/sr_poll.py", line 534, in post_new_urls
    self.dest.connect()
  File "/usr/lib/python3/dist-packages/sarra/sr_ftp.py", line 223, in connect
    self.logger.error("Unable to connect to %s (user:%s)" % self.host, self.user)
TypeError: not enough arguments for format string
2020-02-26 15:17:03,554 [ERROR] Sleeping 30 secs and retry
2020-02-26 15:17:33,584 [DEBUG] poll is sleeping 300 seconds
