### ISSUE TITLE
polling download fails... 

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#309]
2020-02-21 20:00:23,914 [ERROR] Download failed http://www.suominet.ucar.edu///data/ncConusHourly//CsuPWVh_2020.052.17.00.0060_nc
2020-02-21 20:00:23,914 [DEBUG] Exception details:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarra/sr_util.py", line 501, in download
    self.set_local_file_attributes(new_file,msg)
  File "/usr/lib/python3/dist-packages/sarra/sr_util.py", line 745, in set_local_file_attributes
    if ( msg.partstr[0:2] == '1,' ) :
TypeError: 'NoneType' object is not subscriptable

**Comment by petersilva** [comment]
@habilinour or @kurt2x  can you try starting up this poll and see if it works after upgrading to 2.20.02b3 ?

**Comment by kurt2x** [comment]
I can confirm the problem is resolved, data shows up here:
http://ddsr8.cmc.ec.gc.ca/20200305/UCAR-SUOMINET/data/ncConusHourly/CsuPWVh_2020.065.14.00.0060_nc
