### ISSUE TITLE
sr status crash... KeyError:'unknown'

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#310]
sr status
gathering global state:
........... Done reading 1178 procs!
procs, got configs from /home/sarra/.config/sarra
got state files from /home/sarra/.cache/sarra,
logs, analysis - Done.
status:
Component  State      Good?  Qty Configurations-i(r/e)-r(Retry)
---------  -----      -----  --- ------------------------------
audit      running    OK       1
sender     mixed      mult    30
     24 running: bullprep-RI-accessdepot-i1/1, waterobs-to-ppp4-ade-ops-i1/1, ppp4_ade_dev-i2/2, ddi_science_to_accessdepot-ecmwf-i1/1, dms-v2-dev2-i1/1, waterobs-to-ppp4-development-i1/1, ppp3_ade_dev-i2/2, wxo-stage-be01-goes-i1/1, bulletin-emailer-i1/1, waterobs-to-ppp3-ade-ops-i1/1, wxo-stage-be02-goes-i1/1, cmc_science_to_px-stage-i2/2, dms-dev2-v4-i1/1, waterobs-to-ppp3-development-i1/1, bullprep-meteocode-sender-i1/1, cmc_science_to_pds-dev-i5/5, bullprep-text-sender-i1/1, bullprep-circuit-sender-i1/1, cisdaslnx1-i3/3, mage-mrwo-mcgill-ca-i1/1, wxo-dev-be01-goes-i1/1, cmc_science_to_pds-stage-i5/5, dms-dev1-i1/1, wxo-dev-be01-i1/1
Traceback (most recent call last):
  File "/usr/bin/sr", line 9, in <module>
    load_entry_point('metpx-sarracenia==2.20.2b2', 'console_scripts', 'sr')()
  File "/usr/lib/python3/dist-packages/sarra/sr.py", line 1045, in main
    sys.exit(gs.status())
  File "/usr/lib/python3/dist-packages/sarra/sr.py", line 958, in status
    status[self.configs[c][cfg]['status']].append( cfg+sfx )
KeyError: 'unknown'

**Comment by petersilva** [comment]
priority assigned based on it preventing deployment to some important systems.
