### ISSUE TITLE
Stateful Queue Binding maintenance

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#35]
currently, when one starts up sr_subscribe with

subtopic A

then stops the sr_subscribe, and edits the file to show

subtopic B

Then restart sr_subscribe, the result is that both bindings are set on the queue. The new binding is added, but the old binding is not, so the result is a subscription to A and B, rather than just B.

The reason for this is that the queue must be preserved one wishes to receive items which arrive during transient failures of the consumer. But the very permanence of the queue causes the bindings previously in place to be preserved across instances.

One can correct this unfortunate effect by invoking sr_subscribe with --reset option, to delete the queue and with it, the old binding. The queue will be re-created with only the new binding. Unfortunately that has the effect of discarding all items already queued.

AMQP does not provide any way to query what bindings are in effect, nor does it allow to delete bindings without specifying them exactly. In order to delete a binding one must know exactly what it is. When the configuration has changed, the program no longer has access to what the binding was before the change, and so it does not have the information required to delete the old bindings.

To correct the behaviour, one needs to treat bindings as statefully. Currently, sr_subscribe stores the name of the queue in the user_cache_dir. One would need to add more content to the state directory to document the bindings in place when the subscribe was initiated.

When sr_subscribe starts up, need to compare the stored bindings with the bindings set by the current configuration, removing obsolete ones and adding the new ones. Then save the bindings to the binding state file.

This was all discussed with sr_subscribe as an example, but it applies equally to all consumers.

Was: https://sourceforge.net/p/metpx/feature-requests/49/

**Comment by michelgrenier** [comment]
saving previous bindings and cleaning up what is not matching the config options on restart may
work... but needs to be tested if this example would work....  
 ex. old = exchange x, subtopic *.a.#
      new =  exchange = x subtopic = *.a.b.#   

unbonding    subtopic *.a.# ...   should not break  binding   subtopic *.a.b.# ...
if this is true... it is easy.

**Comment by petersilva** [comment]
That will work fine... detail:  you want to:   1. diff the bindings... 2. apply net new ones, 3. remove net removed ones. in that order.

btw... AMQP supports this, but I don´t think Sarracenia does...

exchange XA

subtopic A

exchange XB

subtopic B

does binding a single subscriber to multiple exchanges work?  I don´t think so... I don´t know if it should.

**Comment by michelgrenier** [comment]
yes this should work...
everytime a subtopic is declared in the options, the queue binding list is appended like this :+1: self.bindings.append( (self.exchange,key) )
and this is used later for the queue settings.

**Comment by michelgrenier** [comment]
did not know that colon auto generate a thumb up... did not mean that

**Comment by michelgrenier** [comment]
I knew such bindings could be done so I implemented it.
It might be something that may become useful because it gives flexibility

**Comment by michelgrenier** [comment]
there is no code for binding deletion on a queue  in sr_amqp I had not think about this .

**Comment by petersilva** [comment]
you implemented it now? or it has been there already a long time?

**Comment by petersilva** [comment]
I´m pretty sure the C code doesn´t support this... if this works, then need to open an issue in Sarrac to document the difference in implementation.

**Comment by michelgrenier** [comment]
Yes in there now... dont recall since when

**Comment by michelgrenier** [comment]
remember that I don t really code now... it is for the young pops :-)

**Comment by michelgrenier** [comment]
Done

**Comment by petersilva** [comment]
Thanks!

**Comment by petersilva** [comment]
Still the issue of changing bindings involving adding new ones, and then deleting old ones remains.

**Comment by petersilva** [comment]
## Cases

1. adding new bindings (no difference from current.)

    * current thing will re-do the old bindings (harmless)
    * and add the new bindings (fine.)
    * no change needed.
    
2. changing bindings (some binding removed.)  

    * current thing: just leaves them you need to do a *cleanup* and then it becomes case 1.
    * ideally if we can call *unbind* after... then that avoids having to do a cleanup.
   
3. changing queue parameters e.g.

   * if someone changes *expire* then today, the queue declare fails with "PRECONDITION failed" and
      the expire setting never takes effect (at least) or nothing works (because you loop trying to get the declare to work.
   * in the current state, one must do a *cleanup* to remove the old queue (everything queued) and then
      declare it in the new settings.
   * the best we can do is, rather than the inscrutable PRECONDITION FAILED message, we say *cleanup required*
     and refuse to start or foreground until it is done.
 
5. change queue name...
   * need to remove old queue ... then becomes case 1.

**Comment by petersilva** [comment]
Implementation strategies:

* read old_subscriptions... 
* create new subscriptions from settings.... using old ones as inspiration...
  * for queue name settings with substitutable values use the ones from the old_...
* compare the old and new to find:
  * bindings to remove.
  * queues to remove.
  * whether a *cleanup* is needed or not.

If a *cleanup* is needed, refuse to foreground or start.

**Comment by reidsunderland** [comment]
I think there's a bug with the credentials refactor. If a credential doesn't exist, it gets this error:

```
2024-09-27 13:14:51,421 2023550 [ERROR] sarracenia.config.credentials isValid credential not found
2024-09-27 13:14:51,421 2023550 [CRITICAL] root validate_urlstr bad credential amqp://feeder@example.com/
Traceback (most recent call last):
  File "/net/local/home/sunderlandr/.local/bin/sr3", line 8, in <module>
    sys.exit(main())
  File "/net/local/home/sunderlandr/sr3/sarracenia/sr.py", line 3089, in main
    gs = sr_GlobalState(cfg, cfg.configurations)
  File "/net/local/home/sunderlandr/sr3/sarracenia/sr.py", line 1324, in __init__
    self._read_configs()
  File "/net/local/home/sunderlandr/sr3/sarracenia/sr.py", line 333, in _read_configs
    cfgbody.parse_file(cfg,c)
  File "/net/local/home/sunderlandr/sr3/sarracenia/config/__init__.py", line 1539, in parse_file
    self.parse_line( component, cfg, cfname, lineno, l.strip() )
  File "/net/local/home/sunderlandr/sr3/sarracenia/config/__init__.py", line 1755, in parse_line
    setattr(self, k, v)
  File "/net/local/home/sunderlandr/sr3/sarracenia/config/__init__.py", line 994, in broker
    ok, cred_details = self.credentials.validate_urlstr(v)
  File "/net/local/home/sunderlandr/sr3/sarracenia/config/credentials.py", line 504, in validate_urlstr
    cred_details = credentials.Credential()
NameError: name 'credentials' is not defined. Did you mean: 'Credential'?
```
