### ISSUE TITLE
hash tag (#) in the password for sftp credentials in credentials.conf results in problems for sr_sender instances

### ISSUE THREAD

**Issue by EricFunk** [MetPX/sarracenia#364]
Having a # in the password of an sftp site in credentials.conf results in the system not using the password field at all.

Using the password directly in the 'destination' field results in the sr_sender instance not starting at all and tossing an error. for instance if I use '123$#45' as a password I would get the following error on startup:

```
Traceback (most recent call last):

  File "/usr/bin/sr_sender", line 11, in <module>
    load_entry_point('metpx-sarracenia===2.20.08p1', 'console_scripts', 'sr_sender')()
  File "/usr/lib/python3/dist-packages/sarra/sr_sender.py", line 347, in main
    sender = sr_sender(config,args,action)
  File "/usr/lib/python3/dist-packages/sarra/sr_instances.py", line 63, in __init__
    self.configure()
  File "/usr/lib/python3/dist-packages/sarra/sr_config.py", line 599, in configure
    self.check()
  File "/usr/lib/python3/dist-packages/sarra/sr_sender.py", line 130, in check
    ok, self.details = self.credentials.get(self.destination)
  File "/usr/lib/python3/dist-packages/sarra/sr_credentials.py", line 114, in get
    ok, details = self.resolve(urlstr, url)
  File "/usr/lib/python3/dist-packages/sarra/sr_credentials.py", line 266, in resolve
    if url.port          != u.port     : continue
  File "/usr/lib/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '123$'z
```

I tried escaping it with \# and %23 with no luck.

I believe its an issue in sarracenia where it uses urllib.parse.urlparse which doesn't handle # and sarracenia doesn't account for that.

**Comment by petersilva** [comment]
root cause here is this: https://bugs.python.org/msg375109

the urlparse does not interpret the % encoding... you need to interpret it at a later
stage, using urllib.parse.unquote( ) when you try to use the password.

**Comment by petersilva** [comment]
%23 for # and %40 for @

**Comment by petersilva** [comment]
both main branches addressed.
