### ISSUE TITLE
vip does not work

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#410]
working with sr3 on wmo testing... tried a vip setting, and it does not work. need to test on localhost.

**Comment by petersilva** [comment]
test with 
vip 127.0.0.1

and it should always have it, and then with 1287.0.0.124 that will never have it.

**Comment by petersilva** [comment]
I cherry-picked the patch into v03_wip, as it passes all the flow tests.  But there is still a problem:
to reproduce:

* sr3 add subscribe/hpfx_amis.conf
* sr3 edit subscribe/hpfx_amis.conf #  add vip 127.0.0.30 ... a non-existent address that will not be on the host.
* mkdir /tmp/hpfx_amis # build the directory the config will download to.

result:


```
fractal% sr3 --debug foreground  subscribe/hpfx_amis.conf
2021-09-29 17:03:31,719 [INFO] sarracenia.flow loadCallbacks plugins to load: ['sarracenia.flowcb.retry.Retry', 'sarracenia.flowcb.v2wrapper.V2Wrapper', 'sarracenia.flowcb.gather.message.Message']
2021-09-29 17:03:31,722 [DEBUG] sarracenia.flowcb.retry __init__ sr_retry __init__
2021-09-29 17:03:31,722 [DEBUG] sarracenia.diskqueue __init__  work_retry_00 __init__
2021-09-29 17:03:31,722 [DEBUG] sarracenia.diskqueue __init__ name=work_retry_00 logLevel=debug
2021-09-29 17:03:31,722 [DEBUG] sarracenia.diskqueue __init__  post_retry_000 __init__
2021-09-29 17:03:31,722 [DEBUG] sarracenia.diskqueue __init__ name=post_retry_000 logLevel=debug
2021-09-29 17:03:31,722 [DEBUG] sarracenia.flowcb.retry __init__ logLevel=debug
2021-09-29 17:03:31,857 [DEBUG] amqp _on_start Start from server, version: 0.9, properties: {'capabilities': {'publisher_confirms': True, 'exchange_exchange_bindings': True, 'basic.nack': True, 'consumer_cancel_notify': True, 'connection.blocked': True, 'consumer_priorities': True, 'authentication_failure_close': True, 'per_consumer_qos': True, 'direct_reply_to': True}, 'cluster_name': 'rabbit@hpfx2.collab.science.gc.ca', 'copyright': 'Copyright (C) 2007-2019 Pivotal Software, Inc.', 'information': 'Licensed under the MPL.  See http://www.rabbitmq.com/', 'platform': 'Erlang/OTP 21.3', 'product': 'RabbitMQ', 'version': '3.7.13'}, mechanisms: [b'AMQPLAIN', b'PLAIN'], locales: ['en_US']
2021-09-29 17:03:31,901 [DEBUG] amqp __init__ using channel_id: 1
2021-09-29 17:03:31,919 [DEBUG] amqp _on_open_ok Channel open
2021-09-29 17:03:31,945 [INFO] sarracenia.moth.amqp __getSetup queue declared q_anonymous_subscribe.hpfx_amis.92365575.60601390 (as: amqps://anonymous@hpfx.collab.science.gc.ca/) 
2021-09-29 17:03:31,945 [INFO] sarracenia.moth.amqp __getSetup binding q_anonymous_subscribe.hpfx_amis.92365575.60601390 with v02.post.*.WXO-DD.bulletins.alphanumeric.# to xpublic (as: amqps://anonymous@hpfx.collab.science.gc.ca/)
2021-09-29 17:03:31,958 [DEBUG] sarracenia.moth.amqp __getSetup getSetup ... Done!
2021-09-29 17:03:31,958 [DEBUG] sarracenia.config check_undeclared_options missing defaults: {'exchange_suffix', 'reconnect', 'set_passwords', 'report_exchange', 'exchange_split', 'pump_flag', 'poll_without_vip', 'declare_exchange', 'blocksize', 'inplace', 'retry_mode', 'post_exchange_split', 'post_on_start', 'pipe', 'destination', 'dry_run', 'restore', 'post_exchange', 'path', 'follow_symlinks', 'post_exchange_suffix', 'force_polling', 'source_from_exchange', 'realpath_filter', 'save', 'bind_queue', 'declare_queue', 'report_daemons', 'sanity_log_dead', 'cache_stat', 'header'}
2021-09-29 17:03:31,958 [DEBUG] sarracenia.flow run working directory: /home/peter/Sarracenia/sr3/sarracenia/flow
2021-09-29 17:03:31,958 [INFO] sarracenia.flow run options:
_Config__admin=amqp://bunnymaster@localhost, _Config__broker=amqps://anonymous@hpfx.collab.science.gc.ca, _Config__post_broker=None,
accel_threshold=0, accept_unmatched=True, action='foreground', attempts=3, auto_delete=False, baseDir=None, baseUrl_relPath=False, batch=100,
bind=True, bindings=[('xpublic', ['v02', 'post'], ['*.WXO-DD.bulletins.alphanumeric.#'])], bufsize=1048576, bytes_per_second=None, bytes_ps=0,
cfg_run_dir='/home/peter/.cache/sr3/subscribe/hpfx_amis', chmod=0, chmod_dir=509, chmod_log=384, configurations=['subscribe/hpfx_amis.conf'],
currentDir=None, dangerWillRobinson=False, debug=True, declare=True, declared_exchanges=[],
declared_users={'tfeed': 'feeder', 'tsub': 'subscriber', 'tsource': 'source', 'anonymous': 'subscriber', 'ender': 'source', 'eggmeister': 'subscriber'},
delete=False, destfn_script=None, directory='/tmp/hpfx_amis/', discard=False, documentRoot=None, download=True, durable=True,
env_declared=['FLOWBROKER', 'MQP', 'SFTPUSER', 'TESTDOCROOT'], events='create|delete|link|modify', exchange='xpublic', expire=600.0,
feeder=amqp://tfeed@localhost, file_time_limit=5184000.0, filename='WHATFN', fixed_headers={}, flatten='/', hostdir='fractal', hostname='fractal',
housekeeping=30, imports=[], inflight=None, inline=False, inline_encoding='guess', inline_max=4096, inline_only=False, instances=5,
integrity_arbitrary_value=None, integrity_method='sha512', logFormat='%(asctime)s [%(levelname)s] %(name)s %(funcName)s %(message)s',
logLevel='debug', log_reject=False, lr_backupCount=5, lr_interval=1, lr_when='midnight',
masks=[('.*', '/tmp/hpfx_amis/', 'WHATFN', re.compile('.*'), True, False, 0, False, '/')], message_count_max=0, message_rate_max=0,
message_rate_min=0, message_strategy={'reset': True, 'stubborn': True, 'failure_duration': '5m'}, message_ttl=0, mirror=False, no=0,
nodupe_basis='path', nodupe_ttl=0, notify_only=False, overwrite=True,
pid_filename='/home/peter/.cache/sr3/subscribe/hpfx_amis//subscribe_hpfx_amis_00.pid', plugins=[], post_baseDir=None, post_baseUrl=None,
post_documentRoot=None, post_exchanges=[], post_topicPrefix=['v02', 'post'], prefetch=25, preserve_mode=True, preserve_time=True,
program_name='subscribe', pstrip=False, queue_filename='/home/peter/.cache/sr3/subscribe/hpfx_amis/subscribe.hpfx_amis.anonymous.qname',
queue_name='q_anonymous_subscribe.hpfx_amis.92365575.60601390', randid='16bb', randomize=False, realpath_post=False, rename=None, report_back=False,
reset=False, retry_path='/home/peter/.cache/sr3/subscribe/hpfx_amis//subscribe_hpfx_amis_00.retry', retry_ttl=600.0, settings={}, sleep=0.1,
statehost=False, strip=0, subtopic=[], timeout=300, tls_rigour='normal', topicPrefix=['v02', 'post'], undeclared=[], users=False,
v2plugin_options=[], v2plugins={}, vhost='/', vip='127.0.0.37'
2021-09-29 17:03:31,958 [INFO] sarracenia.flow run callbacks loaded: ['sarracenia.flowcb.retry.Retry', 'sarracenia.flowcb.v2wrapper.V2Wrapper', 'sarracenia.flowcb.gather.message.Message']
2021-09-29 17:03:31,959 [INFO] sarracenia.flowcb.v2wrapper on_time v2 run on_start
Traceback (most recent call last):
  File "/home/peter/Sarracenia/sr3/sarracenia/instance.py", line 214, in <module>
    i.start()
  File "/home/peter/Sarracenia/sr3/sarracenia/instance.py", line 205, in start
    self.running_instance.run()
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/__init__.py", line 343, in run
    total_messages += last_gather_len
UnboundLocalError: local variable 'last_gather_len' referenced before assignment
2021-09-29 17:03:32,028 [ERROR] root run_command subprocess.run failed err=Command '['/usr/bin/python3', '/home/peter/Sarracenia/sr3/sarracenia/instance.py', '--no', '0', '--debug', 'foreground', 'subscribe/hpfx_amis.conf']' returned non-zero exit status 1.
2021-09-29 17:03:32,028 [DEBUG] root run_command Exception details:
Traceback (most recent call last):
  File "/home/peter/Sarracenia/sr3/sarracenia/sr.py", line 999, in run_command
    subprocess.run(cmd_list, check=True)
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/peter/Sarracenia/sr3/sarracenia/instance.py', '--no', '0', '--debug', 'foreground', 'subscribe/hpfx_amis.conf']' returned non-zero exit status 1.

fractal% 

```

So there is still more to do.
