### ISSUE TITLE
NameError: name 'isnumeric' is not defined

### ISSUE THREAD

**Issue by endlisnis** [MetPX/sarracenia#486]
When trying to use `inflight tmp/` in my sr3 config file, I get this message:
```
$ ~/.local/bin/sr3 restart subscribe/rolf
Traceback (most recent call last):
  File "/home/rolf/.local/bin/sr3", line 33, in <module>
    sys.exit(load_entry_point('metpx-sr3', 'console_scripts', 'sr3')())
  File "/home/rolf/weather/sr3/sarracenia/sr.py", line 1952, in main
    gs = sr_GlobalState(cfg, cfg.configurations)
  File "/home/rolf/weather/sr3/sarracenia/sr.py", line 980, in __init__
    self._read_configs()
  File "/home/rolf/weather/sr3/sarracenia/sr.py", line 292, in _read_configs
    cfgbody.parse_file(cfg)
  File "/home/rolf/weather/sr3/sarracenia/config.py", line 1137, in parse_file
    if isnumeric(v[:-1]):
NameError: name 'isnumeric' is not defined
```

**Comment by petersilva** [comment]
sigh... fixed... will push soon.

**Comment by petersilva** [comment]
this should have been caught by unit tests... leaving open for unit testing coverage hint.

**Comment by endlisnis** [comment]
I tried an updated pull from git, and I now get this:

```
Traceback (most recent call last):
  File "/home/rolf/weather/sr3/sarracenia/instance.py", line 226, in <module>
    i.start()
  File "/home/rolf/weather/sr3/sarracenia/instance.py", line 217, in start
    self.running_instance.run()
  File "/home/rolf/weather/sr3/sarracenia/flow/__init__.py", line 346, in run
    self.do()
  File "/home/rolf/weather/sr3/sarracenia/flow/subscribe.py", line 27, in do
    self.do_download()
  File "/home/rolf/weather/sr3/sarracenia/flow/__init__.py", line 935, in do_download
    new_inflight_path = self.o.inflight + new_file
NameError: name 'new_file' is not defined
```

**Comment by petersilva** [comment]
uh... ok... second patch. tested and adjusted debug output to prove it was doing the right thing this time.

**Comment by endlisnis** [comment]
The second patch works for me.
