### ISSUE TITLE
figure out whether sr3_poll on a file url works.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#585]
currently we use poll for remote resources, via sftp, ftp, and http with various web services.
For local file systems, we can use linux INOTIFY kernel facility, except in some case that does not work (e.g: in HPC where file i/o can happen on many nodes and must have watch running on all nodes as a consequence)  so we have the force_polling option in watch... which seems odd given the existence of the poll component... why don't we just use that? indeed... 

Need to investigate whether polling with a destination as a file url works, and if so, document it as another option.

It  seems inelegant for this not to work.

**Comment by MagikEh** [comment]
## Context
KH was just attempting this on a machine due to a NFS mount that needed to be 'watched' but `sr_watch` wasn't able to be activated because the NFS server wasn't sharing any inotify messages. @andreleblanc11 suggested he use a poll with the `pollUrl file://....` option, below is a summary of the poll:

```sh
pollUrl file:///net/local/home/remote_nfs_user
scheduled_interval 300
post_baseUrl http://${HOSTNAME}/~remote_nfs_user/
path /net/local/home/remote_nfs_user

documentRoot /net/local/home/remote_nfs_user/
strip net/local/home/remote_nfs_user

nodupe_ttl 10d
fileAgeMax 11d
acceptUnmatched False
# Don't want the older dataset
accept .*DIR1.*.gif
accept .*DIR2.*.gif
accept .*DIR3.*.gif
accept .*DIR4.*.gif

logLevel debug
```

## Issue
He ran into an issue where polling the `remote_nfs_user`'s directory as the system `sarra` user hit a permissions issue for a single sub directory and immediatly quit out, the log showed:
```
[DEBUG]   sarracenia.flowcb.scheduled:(calc_next_gather_time) next gather should be in 300s, scheduled for 2025-05-03 12:02:10.209000+00:00 (default_wait
[INFO]    sarracenia.flowcb.scheduled.poll:(gather)           poll routine will run
[DEBUG]   sarracenia.transfer.file:(connect)                  sr_file connect file: ///net/local/home/remote_nfs_user
[DEBUG]   sarracenia.flowcb.poll:(poll_directory)             cd /net/local/home/remote_nfs_user/
[DEBUG]   sarracenia.transfer.file:(cd)                       sr_file cd /net/local/home/remote_nfs_user/
[DEBUG]   sarracenia.transfer.file:(ls)                       sr_file ls
[WARNING] sarracenia.flowcb.poll:(lsdir)                      dest. lsdir: Could not ls directory
[DEBUG]   sarracenia.flowcb.poll:(lsdir)                      Exception details:
                                                              Traceback (most recent call last):
                                                                File "/usr/lib/python3/dist-packages/sarracenia/flowcb/poll/_init _. py", line 392, in lsdir
                                                                  ls = self.dest. ls()
                                                                File "/usr/lib/python3/dist-packages/sarracenia/transfer/file.py", line 175, in ls
                                                                  self. ls_python(self.path)
                                                                File "/usr/lib/python3/dist-packages/sarracenia/transfer/file.py", line 182, in ls_python
                                                                  if self.recursive: self.ls_python(dst)
                                                                File "/usr/lib/python3/dist-packages/sarracenia/transfer/file.py", line 179, in ls_python
                                                                  for x in os. listdir(dpath):
                                                                PermissionError: [Errno 13] Permission denied: '/net/local/home/remote_nfs_user/.ssh'
[DEBUG]   sarracenia.flowcb.poll:(poll)                       poll_directory returned: 0
[DEBUG]   sarracenia.transfer.file:(close)                    sr_file close
[DEBUG]   sarracenia.flow filter:(start)                      len(incoming)=0, rejected=0
[DEBUG]   sarracenia.flow filter:(end)                        len(incoming)=0, rejected=0
```

### Bug Definition:
I think the sr3 bug here is that the `sarracenia.flowcb.poll:lsdir()`  [function's try block](https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/poll/__init__.py#L391-L417) is too encompassing, and not allowing [the for loop](https://github.com/MetPX/sarracenia/blob/development/sarracenia/flowcb/poll/__init__.py#L404) to consume the remaining directories that might not error out when acted on..


## Bandaid Fix
Changing the `path` directive to be more precise is being used as a band-aid fix:
```sh
path /net/local/home/remote_nfs_user/DIR1
path /net/local/home/remote_nfs_user/DIR2
path /net/local/home/remote_nfs_user/DIR3
path /net/local/home/remote_nfs_user/DIR4
```
(the above still has the potential to miss messages if there's a single sub directory that has non-sarra user permissions)

**Comment by petersilva** [comment]
The *force_polling* option is available for use in *watch* on file systems that do not generate INOTIFY events.  

```

force_polling on

```
in the *watch*  config.

for getting it to work with polling... hmm... that is kind of a long term goal... merging file watching and polling of file urls... have not looked into it much so far.

**Comment by petersilva** [comment]
might also want to check the *recursive* option.... if it is off... it won´t look  in sub-dirs.

**Comment by petersilva** [comment]
https://metpx.github.io/sarracenia/Reference/sr3_options.7.html#force-polling-flag-default-false

**Comment by MagikEh** [comment]
> might also want to check the _recursive_ option.... if it is off... it won´t look in sub-dirs.

I did have a check of that option, it is enabled by default!

> The _force_polling_ option is available for use in watch on file systems that do not generate INOTIFY events.

I'll mention this to KH as another option to test in order make his configs simpler!

**Comment by petersilva** [comment]
The original version of *watch* was a tree walking aka polling version, and the you need that logic in *watch* anyways because you have to set flags in each sub-directory to start INOTIFY event generation.  The inotify logic was added afterwards, for larger trees.   INOTIFY is more efficient and quicker, so we made that the default once it was available.

I agree with @andreleblanc11  that polling a file url makes tremendous intuitive sense, and never tried to actually get that working properly/cleanly.  It should be conceptually the same as a *watch* with *force_polling*, but reality is that using *poll* with file Url´s was never fully tested or explored.

**Comment by petersilva** [comment]
Another thing that could be considered, is running the watch on the NFS server, instead of the client.  It would be a fun experiment to see if the INOTIFY events are created there, and so you could get the benefit of lower overhead file watching... 
obviously not possible with NAS boxes.
