### ISSUE TITLE
WARNING: No sr3 configuration found.

### ISSUE THREAD

**Issue by n-a-t-e** [MetPX/sarracenia#632]
After installing with pip:

```pip install metpx-sr3[amqp,mqtt,vip]```

When I run `sr3 list examples`, or any other `sr3` command, I get:

```
WARNING: No sr3 configuration found.
WARNING: No sr3 configuration state or log files found.
Traceback (most recent call last):
  File "/anaconda3/envs/ssv/bin/sr3", line 8, in <module>
    sys.exit(main())
  File "/anaconda3/envs/ssv/lib/python3.10/site-packages/sarracenia/sr.py", line 2222, in main
    gs = sr_GlobalState(cfg, cfg.configurations)
  File "/anaconda3/envs/ssv/lib/python3.10/site-packages/sarracenia/sr.py", line 1028, in __init__
    self._resolve()
  File "/anaconda3/envs/ssv/lib/python3.10/site-packages/sarracenia/sr.py", line 792, in _resolve
    self._resolve_brokers()
  File "/anaconda3/envs/ssv/lib/python3.10/site-packages/sarracenia/sr.py", line 700, in _resolve_brokers
    o=self.default_cfg
AttributeError: 'sr_GlobalState' object has no attribute 'default_cfg
```

I've tried this on Mac Big Sur and Centos 7, same result.

Thanks!

**Comment by petersilva** [comment]
ef6cd76bc2a0ab999ad27a8cac544cb5b1ba02d9 fixed.

**Comment by petersilva** [comment]
unfortunately I noticed this after releasing 3.0.28... if you install with pip it will still have the error.  It will be included in a future release.  On linux, you can get around it with:

mkdir ~/.config ~/.cache ~/.config/sr3 ~/.cache/sr3

on MACOS... the placement is different...

something like: 
mkdir ~/Library/Caches/ ~/Library/Caches/sr3 

and something similar for the configuration directories.
