### ISSUE TITLE
SFTP url's with absolute and relative paths, a discussion.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#639]
sftp is a particular protocol in that it path specified at the end is an actual path, and not something relative from a document root.

sr3 treats all sftp paths as absolute currently. In some other software, there is a convention for using an absolute path in an SFTP url is to use the double slash,

e.g.:

```
     sftp://user@host/my_favourite_dir   -- relative path.
    sftp://user@host//home/user/my_favourite_dir  -- absolute path.

```

The relative path is expected to be relative to the user's home directory.
*Scp* has a different convention  *scp user@host:path* use of the colon separator allows for easy disambiguation.

sources:
* https://www.arubanetworks.com/techdocs/AOS-CX/10.07/HTML/5200-7851/Content/Chp_Cfg_FW_mgt/FW_mgt_cmds/sft-url.htm

It's just a convention, and sometimes it works, but sometimes it doesn't.  there are popular tools that don't support it, like curl:
```
curl sftp://peter@localhost/dirA.sums

```
fails even though the file is in peter's home directory... Need to use:

```

curl sftp://peter@localhost/~/dirA.sums

```

So there is a second possible notation.  Note that one must be implemented on the client.  If you send ~/dirA.sums to
an SFTP server, it will not interpret it correctly, so need to remove the ~/ in the sftp protocol driver... hmm... that actually sounds relatively easy.

Should we support relative paths in sftp URLs?  If so, which convention to follow?

I think ~ is the easier and clearer one.

**Comment by petersilva** [comment]
ok, so manually built a paramiko session to open an sftp connection to localhost.
* when you login, sftp.getcwd() returns None.
* when you then sftp.listdir() it lists the home directory.
* if you sftp.chdir('/tmp'), then sftp.getcwd() -> "/tmp", and listdir() lists that directory... ok.
* sftp.chdir(None) , then sftp.getcwd() -> None, listdir() gives you the home directory.

So seeing "/~" in the path part of a URL, could be interpreted as None... but if you want ~/hoho?
you have to do make it relative.... issue an sftp.chdir("hoho") (assuming you just established the connection.
if you are somewhere else, then it looks like it must be done in two steps:  chdir(None) to get to home, then
a second, relative one.

**Comment by petersilva** [comment]
I tested another server (polled by @andreleblanc11 originally)

``` 

sftp user@host
sftp> pwd
Remote working directory: /HOME
sftp> chdir .
sftp> pwd
Remote working directory: /HOME
sftp>
sftp> ls /
/HOME
sftp> cd /
sftp> ls
HOME
sftp>
sftp> cd ~
stat remote: No such file or directory
sftp>

``` 

so here / is a chroot, and only /HOME is in it.

**Comment by petersilva** [comment]
discussion conclusion:

* for v03 config:   have baseUrl:  sftp://user@host//    -- double slash denotes abs. path.
* when writing v03 format messages, baseURL looks like that.
* this is incompatible with how v02 interprets fhings, so when writing a v02 message:
   * remove the trailing slashes from the baseUrl
   * prepend relpath with a slash.

**Comment by petersilva** [comment]
another use case to wonder about:
* baseUrl:  sftp://user@host/dir1   -- is dir1 relative or absolute?
* we use sftp://user@host//dir1  to make it absolute.

**Comment by petersilva** [comment]
so... I went to look for a test case, and looked in the flow tests... the static and no_mirror ones have SFTP polls, senders, and subscribers in them , so I figured I would leave static alone, and try modifying the no_mirror flow test  to use absolute paths...

so in the no_mirror  (which is a copy of static) test there is config/poll/sftp_f62, and it posts messages like so:

```
2023-11-23 16:18:50,756 [INFO] sarracenia.flowcb.log after_post posted to exchange: xs_tsource_poll topic: v03.post.home.peter.sarra_devdocroot.sent_by_tsou
rce2send.deeper.than.flat.sender a file with baseUrl: sftp://peter@localhost/ relPath: home/peter/sarra_devdocroot/sent_by_tsource2send/deeper/than/flat/sen
der/Constant.YQ

```

so that is what we expect, a relPath entry that contains an absolute path, but missing the first slash.   That's the same as what @reidsunderland ran into..  now I have a subscriber,
subscribe_q_f71, and it is downloading like so:
```
2023-11-23 16:19:05,611 [DEBUG] sarracenia.flow filter  urlToMatch: sftp://peter@localhost/home/peter/sarra_devdocroot/sent_by_tsource2send/deeper/than/flat
/sender/CACN45_CWAO_050300__WIG_50746 
2023-11-23 16:19:05,607 [INFO] sarracenia.moth.amqp _msgRawToDict body: type: <class 'str'> (314 bytes) {"pubTime": "20231123T211903.827084303", "relPath": 
"home/peter/sarra_devdocroot/sent_by_tsource2send/deeper/than/flat/sender/CACN45_CWAO_050300__WIG_50746", "baseUrl": "sftp://peter@localhost/", "identity": 
{"method": "cod", "value": "sha512"}, "size": 546, "mtime": "20231123T211748", "atime": "20231123T211748"}
2
2023-11-23 16:19:05,616 [INFO] sarracenia.flowcb.log after_accept accepted: (lag: 1.79 ) {  '_deleteOnPost':'{'post_format', 'new_baseUrl', 'new_subtopic', 
'local_offset', 'exchange', 'ack_id', 'new_relPath', 'new_dir', '_format', 'new_file', 'subtopic'}', '_format':'v03', 'ack_id':'11', 'atime':'20231123211834
', 'baseUrl':'sftp://peter@localhost/', 'exchange':'xs_tsource_poll', 'identity':'{  'method':'cod', 'value':'sha512' }', 'local_offset':'0', 'mtime':'20231
123211748', 'new_baseUrl':'sftp://peter@localhost/', 'new_dir':'/home/peter/sarra_devdocroot/recd_by_srpoll_test1', 'new_file':'SRCN40_KWAL_050300___30972',
 'new_relPath':'home/peter/sarra_devdocroot/recd_by_srpoll_test1/SRCN40_KWAL_050300___30972', 'new_subtopic':'['home', 'peter', 'sarra_devdocroot', 'recd_by
_srpoll_test1']', 'parts':'1,224,1,0,0', 'post_format':'v03', 'pubTime':'20231123T211903.827039003', 'relPath':'home/peter/sarra_devdocroot/sent_by_tsource2
send/deeper/than/flat/sender/SRCN40_KWAL_050300___30972', 'size':'224', 'subtopic':'['home', 'peter', 'sarra_devdocroot', 'sent_by_tsource2send', 'deeper', 
'than', 'flat', 'sender']', 'sum':'z,s', 'topic':'['v03', 'post', 'home', 'peter', 'sarra_devdocroot', 'sent_by_tsource2send', 'deeper', 'than', 'flat', 'se
nder']' }

2023-11-23 16:19:06,397 [DEBUG] sarracenia.transfer.sftp cd sr_sftp cd /home/peter/sarra_devdocroot/sent_by_tsource2send/deeper/than/flat/sender
2023-11-23 16:19:06,408 [DEBUG] sarracenia.flow download Beginning fetch of sftp://peter@localhost/home/peter/sarra_devdocroot/sent_by_tsource2send/deeper/t
han/flat/sender/CACN45_CWAO_050300__PZC_05842  into CACN45_CWAO_050300__PZC_05842 0-733
2023-11-23 16:19:06,408 [DEBUG] sarracenia.transfer set_sumalgo sr_proto set_sumalgo cod
2023-11-23 16:19:06,408 [DEBUG] sarracenia.flow download hasAccel=True, thresh=0, len=734, remote_off=0, local_off=0 inflight=CACN45_CWAO_050300__PZC_05842
2023-11-23 16:19:06,408 [DEBUG] sarracenia.transfer.sftp get sr_sftp get CACN45_CWAO_050300__PZC_05842 CACN45_CWAO_050300__PZC_05842 0 0 734
2023-11-23 16:19:06,409 [DEBUG] sarracenia.transfer read_write sr_proto read_write
2023-11-23 16:19:06,429 [DEBUG] sarracenia.flow do_download downloaded ok: /home/peter/sarra_devdocroot/recd_by_srpoll_test1/CACN45_CWAO_050300__PZC_05842
2023-11-23 16:19:06,429 [DEBUG] sarracenia.flow do_download chdir /home/peter/sarra_devdocroot/recd_by_srpoll_test1
2023-11-23 16:19:06,429 [DEBUG] sarracenia.flow download sftp_transport download relPath=home/peter/sarra_devdocroot/sent_by_tsource2send/deeper/than/flat/s
ender/SAIY32_LIIB_050250___30980

2023-11-23 16:19:06,504 [INFO] sarracenia.flowcb.log after_work downloaded ok: /home/peter/sarra_devdocroot/recd_by_srpoll_test1/SRCN40_KWAL_050258___68757 
2023-11-23 16:19:06,504 [INFO] sarracenia.flowcb.log after_work message: {  '_deleteOnPost':'{'post_format', 'data_checksum', 'new_baseUrl', 'local_offset',
 'exchange', 'new_relPath', 'old_format', 'old_subtopic', 'new_subtopic', 'new_dir', 'report', '_format', 'new_path', 'old_relPath', 'onfly_checksum', 'new_
file', 'subtopic', 'new_inflight...}', '_format':'v03', 'atime':'20231123211748', 'baseUrl':'sftp://peter@localhost/', 'contentType':'text/plain', 'data_che
cksum':'None', 'exchange':'xs_tsource_poll', 'identity':'{  'method':'cod', 'value':'sha512' }', 'local_offset':'0', 'mtime':'20231123211748', 'new_baseUrl'
:'sftp://peter@localhost/', 'new_dir':'/home/peter/sarra_devdocroot/recd_by_srpoll_test1', 'new_file':'SRCN40_KWAL_050258___68757', 'new_inflight_path':'SRC
N40_KWAL_050258___68757', 'new_path':'/home/peter/sarra_devdocroot/recd_by_srpoll_test1/SRCN40_KWAL_050258___68757', 'new_relPath':'home/peter/sarra_devdocr
oot/recd_by_srpoll_test1/SRCN40_KWAL_050258___68757', 'new_subtopic':'['home', 'peter', 'sarra_devdocroot', 'recd_by_srpoll_test1']', 'old_format':'v03', 'o
ld_relPath':'home/peter/sarra_devdocroot/sent_by_tsource2send/deeper/than/flat/sender/SRCN40_KWAL_050258___68757', 'old_subtopic':'['home', 'peter', 'sarra_
devdocroot', 'sent_by_tsource2send', 'deeper', 'than', 'flat', 'sender']', 'onfly_checksum':'None', 'parts':'1,251,1,0,0', 'post_format':'v03', 'pubTime':'2
0231123T211903.82653904', 'relPath':'home/peter/sarra_devdocroot/recd_by_srpoll_test1/SRCN40_KWAL_050258___68757', 'report':'{  'code':'201', 'message':'Dow
nload successful /home/peter/sarra_devdocroot/recd_by_srpoll_test1/SRCN40_KWAL_050258___68757', 'timeCompleted':'20231123T211906.227794647' }', 'size':'251'
, 'subtopic':'['home', 'peter', 'sarra_devdocroot', 'recd_by_srpoll_test1']', 'sum':'z,s', 'topic':'['v03', 'post', 'home', 'peter', 'sarra_devdocroot', 're
cd_by_srpoll_test1']' }

```

so the subscriber is managing to download using an absolute path just fine.
I don't understand why this works and @reidsunderland 's case does not.
or I guess  I don't understand whyy the test case passes.

**Comment by petersilva** [comment]
I think I reproduced @reidsunderland 's problem by having an sr3 poll produce sftp messages for a v2 subscriber... but not sure.

**Comment by petersilva** [comment]
so the sr3 is producing posts with a baseURL that ends in /,   and the v2 is ignoring that trailing / so when it looks at the (correct) relPath, it uses it as-is instead of pre-pending the root from the baseUrl.  It looks like a v2 bug.

**Comment by petersilva** [comment]
Tested the two implementations, using the static_flow/config/poll/sftp_f62.conf from sr_insects.  That flow test has a *destination* (v2 option, sr3 would be *pollUrl* ) that ends in localhost/ ... we can change some settings like so (git diff output):

```
-destination     sftp://${SFTPUSER}@localhost/
-directory      ${TESTDOCROOT}/sent_by_tsource2send
+destination     sftp://${SFTPUSER}@localhost/${TESTDOCROOT}
+directory      ${TESTDOCROOT}/sent_by_tsource2send
+base_dir      ${TESTDOCROOT}

```

this should have the effect of moving all the parent directories to the baseUrl, and having just the last directory in the relPath.


In v2, it does nothing to the relPath which still contains an absolute path regardless of what is put in the baseURL, and does not use the directory in the baseURL regardless of it's content.

in v2, all SFTP posts are like so:

```
  baseUrl=sftp://user@host/ignore/anything/here   relpath=/absolute/path/to/something.

  resulting download path:  /absolute/path/to/something.
```
 When posting v2 urls the relative path in the baseUrl is always ignored, and the path is always absolute.



in sr3, the baseURL is meaningful:
```
  baseUrl=sftp://user@host/absolute/path relpath=to/something

  resulting download path: /absolute/path/to/something
```
```
  baseUrl=sftp://user@host/    relpath=/absolute/path/to/something

  note: trailing slash on the baseUrl.

  resulting download path: /absolute/path/to/something  (relative to user's home)
```

```
  baseUrl=sftp://user@host    relpath=to/something

  note: no trailing slash on the baseUrl.

  resulting download path: to/something  (relative to user's home)
```
* but in the downloading, there is an extra / being inserted, and this breaks relative paths on sr3 also.  so this case needs a fix. ( #837 )

**Comment by petersilva** [comment]
v2 incompatibilities with sr3 generates messages.  v2 does not know about directory events,, it fails:
```

2023-11-26 12:27:28,889 [DEBUG] downloading/copying sftp://peter@localhost/home/peter/sarra_devdocroot/sent_by_tsource2send/20200105/WXO-DD/bulletins/alphanumeric
/20200105/WS (scheme: sftp) into WS 
2023-11-26 12:27:28,890 [DEBUG] sftp_transport download
2023-11-26 12:27:28,890 [DEBUG] sftp_transport download connects
2023-11-26 12:27:28,890 [DEBUG] sr_sftp __init__
2023-11-26 12:27:28,890 [DEBUG] sr_sftp init
2023-11-26 12:27:28,890 [DEBUG] iotime 300
2023-11-26 12:27:28,890 [DEBUG] sr_sftp init
2023-11-26 12:27:28,890 [DEBUG] iotime 300
2023-11-26 12:27:28,890 [DEBUG] sr_sftp connect sftp://peter@localhost/
2023-11-26 12:27:28,890 [DEBUG] sr_sftp credentials sftp://peter@localhost/
2023-11-26 12:27:28,890 [DEBUG] sr_credentials has sftp://peter@localhost/
2023-11-26 12:27:28,891 [DEBUG] sr_credentials get in cache sftp://peter@localhost/ sftp://peter@localhost/ None True True False False None
2023-11-26 12:27:28,891 [DEBUG] h u:p s = localhost:22 peter:None None
2023-11-26 12:27:28,891 [DEBUG] check in ssh_config
2023-11-26 12:27:28,891 [DEBUG] h u:p s = localhost:22 peter:None /home/peter/.ssh/id4sarra22
2023-11-26 12:27:29,080 [DEBUG] sr_sftp connect setting timeout 300.000000
2023-11-26 12:27:29,081 [DEBUG] sftp_transport download cd to /home/peter/sarra_devdocroot/sent_by_tsource2send/20200105/WXO-DD/bulletins/alphanumeric/20200105
2023-11-26 12:27:29,081 [DEBUG] sr_sftp cd /home/peter/sarra_devdocroot/sent_by_tsource2send/20200105/WXO-DD/bulletins/alphanumeric/20200105
2023-11-26 12:27:29,082 [DEBUG] Beginning fetch of sftp://peter@localhost//home/peter/sarra_devdocroot/sent_by_tsource2send/20200105/WXO-DD/bulletins/alphanumeric
/20200105/WS  into WS 0--1
2023-11-26 12:27:29,082 [DEBUG] sr_proto set_sumalgo <sarra.sr_config.checksum_d object at 0x7f1cc7eeb790>
2023-11-26 12:27:29,082 [DEBUG] sr_sftp get WS WS.tmp 0 0 0
2023-11-26 12:27:29,083 [DEBUG] sftp_transport close
2023-11-26 12:27:29,083 [DEBUG] sr_sftp close
2023-11-26 12:27:29,083 [DEBUG] sr_sftp init
2023-11-26 12:27:29,083 [DEBUG] iotime 300
2023-11-26 12:27:29,083 [ERROR] Download failed 3 sftp://peter@localhost//home/peter/sarra_devdocroot/sent_by_tsource2send/20200105/WXO-DD/bulletins/alphanumeric/
20200105/WS
2023-11-26 12:27:29,083 [DEBUG] Exception details: 
Traceback (most recent call last):
  File "/home/peter/Sarracenia/v2/sarra/sr_util.py", line 509, in download
    self.get(remote_file,new_lock,remote_offset,msg.local_offset,msg.length)
  File "/home/peter/Sarracenia/v2/sarra/sr_util.py", line 568, in get
    self.proto.get(remote_file, local_file, remote_offset, local_offset, length)
  File "/home/peter/Sarracenia/v2/sarra/sr_sftp.py", line 345, in get
    rw_length = self.read_writelocal(remote_file, rfp, local_file, local_offset, length)
  File "/home/peter/Sarracenia/v2/sarra/sr_util.py", line 297, in read_writelocal
    rw_length = self.read_write( src, dst, length)
  File "/home/peter/Sarracenia/v2/sarra/sr_util.py", line 236, in read_write
    chunk = src.read(self.bufsize)
  File "/usr/lib/python3/dist-packages/paramiko/file.py", line 219, in read
    new_data = self._read(read_size)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_file.py", line 185, in _read
    t, msg = self.sftp._request(
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 907, in _convert_status
    raise IOError(text)
OSError: Failure

```

**Comment by petersilva** [comment]
2nd incompatibility... the relative path being recieved from sr3, vs. v2 only supporting absolute ones:
```

2023-11-26 13:08:08,675 [DEBUG] sr_sftp connect setting timeout 300.000000
2023-11-26 13:08:08,676 [DEBUG] sftp_transport download cd to home/peter/sarra_devdocroot/sent_by_tsource2send/20200105/WXO-DD/meteocode/atl/csv
2023-11-26 13:08:08,676 [DEBUG] sr_sftp cd home/peter/sarra_devdocroot/sent_by_tsource2send/20200105/WXO-DD/meteocode/atl/csv
2023-11-26 13:08:08,677 [DEBUG] sftp_transport close
2023-11-26 13:08:08,677 [DEBUG] sr_sftp close
2023-11-26 13:08:08,677 [DEBUG] sr_sftp init
2023-11-26 13:08:08,677 [DEBUG] iotime 300
2023-11-26 13:08:08,677 [ERROR] Download failed 3 sftp://peter@localhost//home/peter/sarra_devdocroot/sent_by_tsource2send/20200105/WXO-DD/meteocode/atl/csv/2020-01-05T03-00-01Z_FPHX14_r9zf_CC.csv
2023-11-26 13:08:08,677 [DEBUG] Exception details: 
Traceback (most recent call last):
  File "/home/peter/Sarracenia/v2/sarra/sr_util.py", line 455, in download
    proto.cd(cdir)
  File "/home/peter/Sarracenia/v2/sarra/sr_sftp.py", line 103, in cd
    self.sftp.chdir(path)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 659, in chdir
    if not stat.S_ISDIR(self.stat(path).st_mode):
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 493, in stat
    t, msg = self._request(CMD_STAT, path)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 822, in _request
    return self._read_response(num)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 874, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python3/dist-packages/paramiko/sftp_client.py", line 903, in _convert_status
    raise IOError(errno.ENOENT, text)
FileNotFoundError: [Errno 2] No such file

```

**Comment by petersilva** [comment]
the v2 fixes are to address the root cause of the incompatibility, but forcing an upgrade of v2 might be a bit of a high bar.  Will create an on_message plugin for the current version, so we don't have to upgrade... just add an on_message to patch the relPath.

**Comment by petersilva** [comment]
plugin so that v2 flows (from currently deployed versions) can use the messages produced by sr3:

```
user@host:~/master/sarra/plugins$ cat RelativelyAbsolute.py
# convert relative paths to absolute ones, to address v2 bug.
#
class RelativelyAbsolute(object):

      def on_message(self,parent):

          if parent.msg.relpath[0] != '/':
              parent.msg.relpath = '/'+parent.msg.relpath
          return True

self.plugin='RelativelyAbsolute'
user@host:~/master/sarra/plugins$
```

I stuck it in the main v2 repo for now... but it's not tested yet.

**Comment by petersilva** [comment]
Haven't merged the v2 changes to v2dev yet... hmm... because I can't get the dynamic_flow to pass, but It's the same as it was before, so the problem is either long standing or with the test.  It worries me to commit changes without a working dynamic_flow.
Need to take time for that, not a priority for now though.

**Comment by petersilva** [comment]
I think this is taken care of... the v2 code was updated to work with sr3's concept of paths, and the difference between the two is now  well understood by analysts.
