### ISSUE TITLE
crash in watch with some configurations...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#651]
more ~/.config/sr3/watch/hot_directory:
```
post_broker amqps://${FEXUSER}@${FEXSERVER}

path ${HOME}/sr3_hot_directory

# posting local files to be sent.

post_exchange xs_${FEXUSER}_hot_on_${HOSTNAME}
post_baseUrl file:${HOME}/sr3_hot_directory

```

symptom (in the log):
```
0>> crashed: string index out of range
2023-04-22 10:10:05,379 [ERROR] 3173019 sarracenia.flow gather flowCallback plugin <bound method File.gather of <sarracenia.flowcb.gather.file.File object at 0x7fdbce150ca0>> crashed: string index out of range
2023-04-22 10:10:10,385 [ERROR] 3173019 sarracenia.flow gather flowCallback plugin <bound method File.gather of <sarracenia.flowcb.gather.file.File object at 0x7fdbce150ca0>> crashed: string index out of range
2023-04-22 10:10:10,385 [ERROR] 3173019 sarracenia.flow gather flowCallback plugin <bound method File.gather of <sarracenia.flowcb.gather.file.File object at 0x7fdbce150ca0>> crashed: string index out of range
^C2023-04-22 10:10:13,882 [INFO] 3173019 root stop_signal signal 2 received
2023-04-22 10:10:13,882 3173

```

then we turn on add:
```
logLevel debug

```
to the configuration, and we see:

```

0>> crashed: string index out of range
2023-04-22 10:12:38,618 [DEBUG] 3173228 sarracenia.flow gather details:
Traceback (most recent call last):
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/__init__.py", line 975, in gather
    new_incoming = p()
  File "/home/peter/Sarracenia/sr3/sarracenia/flowcb/gather/file.py", line 758, in gather
    return self.wakeup()
  File "/home/peter/Sarracenia/sr3/sarracenia/flowcb/gather/file.py", line 581, in wakeup
    messages.extend(self.process_event(event, src, dst))
  File "/home/peter/Sarracenia/sr3/sarracenia/flowcb/gather/file.py", line 541, in process_event
    return self.post1file(src, lstat)
  File "/home/peter/Sarracenia/sr3/sarracenia/flowcb/gather/file.py", line 469, in post1file
    messages.extend(self.post_file(path, lstat))
  File "/home/peter/Sarracenia/sr3/sarracenia/flowcb/gather/file.py", line 183, in post_file
    msg = sarracenia.Message.fromFileData(path, self.o, lstat)
  File "/home/peter/Sarracenia/sr3/sarracenia/__init__.py", line 454, in fromFileData
    m = sarracenia.Message.fromFileInfo(path, o, lstat)
  File "/home/peter/Sarracenia/sr3/sarracenia/__init__.py", line 499, in fromFileInfo
    msg.updatePaths(o, os.path.dirname(path), os.path.basename(path))
  File "/home/peter/Sarracenia/sr3/sarracenia/__init__.py", line 686, in updatePaths
    if relPath[0] == '/':
IndexError: string index out of range
```

the problem is that the event is being created for the baseDirectory of the post, so relPath resolves to an empty string.

**Comment by petersilva** [comment]
release in 3.00.37
