### ISSUE TITLE
crash in subscriber, trying to mark a retry completed.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#66]
This is in the high performance computing mirroring case, millions of files being copied over hours.
User reports there are 12 subscribers running, and some of them crash once in a while, while the others run without issue.  So the problem is somewhat intermittent.  However it does occur within a day (sometimes within a few hours.)

> 2018-07-13 14:14:29,507 [INFO] file_log downloaded to: ...path elided.../pgsm_temp_modele_00 
> 2018-07-13 14:14:29,508 [INFO] file_age 28087.2 seconds for ... path elided... /pgsm_temp_modele_00 Traceback (most recent call last):
>   File "sr_subscribe.py", line
> 1600, in run
>     ok = self.process_message()
>   File "sr_subscribe.py", line 865,
> in process_message
>     ok = self.__do_tasks__()
>   File "sr_subscribe.py", line 350,
> in __do_tasks__
>     if not plugin(self): return False
>   File "sr_subscribe.py", line
> 1429, in doit_download
>     if self.msg.isRetry: self.consumer.msg_worked()
>   File
> "sr_consumer.py",
> line 281, in msg_worked
>     self.retry.add_msg_to_state_file(self.raw_msg,done=True)
>   File "sr_retry.py",
> line 63, in add_msg_to_state_file
>     self.state_fp =
> self.msg_append_to_file(self.state_fp,self.state_path,message,done)
>   File "sr_retry.py",
> line 241, in msg_append_to_file
>     line = self.encode(message,done)
>   File "sr_retry.py",
> line 115, in encode
>     json_line = json.dumps( [ topic, headers, notice ],
> sort_keys=True ) + '\n'
>   File "/usr/lib64/python3.4/json/__init__.py", line 237, in dumps **kw).encode(obj)
>   File "/usr/lib64/python3.4/json/encoder.py", line 192, in encode chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/lib64/python3.4/json/encoder.py", line 250, in iterencode return _iterencode(o, 0)
> ValueError: Circular reference detected
>  
> During handling of the above exception, another exception occurred:
>  
> Traceback (most recent call last):
>   File "sr_subscribe.py", line 2024, in <module>
>     main()
>   File "sr_subscribe.py", line 2015, in main subscribe.exec_action(action,old)
>   File
> "sr_instances.py", line 294, in exec_action
>     elif action == 'start'      : self.start_parent()
>   File
> "sr_instances.py", line 701, in start_parent
>     self.start()
>   File "sr_subscribe.py", line 1757, in start
>     self.run()
>   File "sr_subscribe.py", line 1604, in run
>     if self.retry_mode : self.consumer.msg_to_retry()
>   File
> "sr_consumer.py", line 271, in msg_to_retry
>     if self.raw_msg.isRetry :
> self.retry.add_msg_to_state_file(self.raw_msg)
>   File "sr_retry.py", line 63, in add_msg_to_state_file
>     self.state_fp = self.msg_append_to_file(self.state_fp,self.state_path,message,done)
>   File "sr_retry.py", line 241, in msg_append_to_file
>     line = self.encode(message,done)
>   File "sr_retry.py", line 115, in encode
>     json_line = json.dumps( [ topic, headers, notice ], sort_keys=True ) + '\n'
>   File "/usr/lib64/python3.4/json/__init__.py", line 237, in dumps  **kw).encode(obj)
>   File "/usr/lib64/python3.4/json/encoder.py", line 192, in encode chunks = self.iterencode(o, _one_shot=True)
>   File "/usr/lib64/python3.4/json/encoder.py", line 250, in iterencode
>     return _iterencode(o, 0)
> ValueError: Circular reference detected
> Exception ignored in: <bound method SSLTransport.__del__ of
> <amqplib.client_0_8.transport.SSLTransport object at 0x3fff9913a8d0>>
> Traceback (most recent call last):
>   File "/usr/lib/python3.4/site-
> packages/amqplib/client_0_8/transport.py", line 97, 
>     in __del__ File "/usr/lib/python3.4/site-packages/amqplib/client_0_8/transport.py", 
>  line 135, in close  File "/usr/lib/python3.4/site-packages/amqplib/client_0_8/transport.py", line 205, in _shutdown_transport
>   File "/usr/lib64/python3.4/ssl.py", line 790, in unwrap
> ssl.SSLError: Underlying socket connection gone (_ssl.c:1787)
>

**Comment by petersilva** [comment]
added try/except around where it crashes so the subscriber does not crash.
29df76474a9eefb3f3058d2f218a5b4619ba4d6d
unfortunately, that likely means the file transfer is not marked as done, and will be attempted again,
if it hits the same problem, then instead of hanging we have a retry loop until expiry... really not a good answer.  It will not crash outright, it will not stop doing productive things, but these useless transfers will occur from time to time.

**Comment by petersilva** [comment]
renamed sr_retry.encode/decode routines, to msgToJSON, and msgFromJSON to improve readability.

**Comment by petersilva** [comment]
released in 2.18.07b2

**Comment by petersilva** [comment]
client has not reported this for years... likely related to timeouts which are fixed in sr3 now...
