### ISSUE TITLE
sr crashes when files with bad names exist in state directory

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#660]
```
   fractal%  cd ~/.cache/sarra/log
   fractal%  touch lll_hoho_haha_hihi_tests.log
   fractal% sr status
    Traceback (most recent call last):
  File "/home/peter/.local/bin/sr", line 33, in <module>
    sys.exit(load_entry_point('metpx-sarracenia', 'console_scripts', 'sr')())
  File "/home/peter/Sarracenia/v2/sarra/sr.py", line 1084, in main
    gs = sr_GlobalState(logger)
  File "/home/peter/Sarracenia/v2/sarra/sr.py", line 726, in __init__
    self._read_logs()
  File "/home/peter/Sarracenia/v2/sarra/sr.py", line 532, in _read_logs
    self._read_logs_dir(self.user_cache_dir)
  File "/home/peter/Sarracenia/v2/sarra/sr.py", line 527, in _read_logs_dir
    if cfg not in self.logs[c]:
  KeyError: 'hoho'
  fractal%

**Comment by reidsunderland** [comment]
That looks good
