### ISSUE TITLE
sr3 crashes parsing a config with a bad regex

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#671]
really strange... 

```

fractal% cat ~/.config/sr3/subscribe/hungry.conf
broker amqp://tsub@localhost

exchange xs_tsource_public

subtopic fruits.#

# print log messages for every file rejected.
logReject on

reject *.qty

# make directories to match the source.
mirror 

# root of the directory where files will be placed.
directory ${HOME}/hungry
fractal%

```
```

fractal% sr3 status
Traceback (most recent call last):
  File "/home/peter/.local/bin/sr3", line 33, in <module>
    sys.exit(load_entry_point('metpx-sr3', 'console_scripts', 'sr3')())
  File "/home/peter/Sarracenia/sr3/sarracenia/sr.py", line 2601, in main
    gs = sr_GlobalState(cfg, cfg.configurations)
  File "/home/peter/Sarracenia/sr3/sarracenia/sr.py", line 1102, in __init__
    self._read_configs()
  File "/home/peter/Sarracenia/sr3/sarracenia/sr.py", line 324, in _read_configs
    cfgbody.parse_file(cfg,c)
  File "/home/peter/Sarracenia/sr3/sarracenia/config.py", line 1389, in parse_file
    self.masks.append(self._build_mask(k, line[1:]))
  File "/home/peter/Sarracenia/sr3/sarracenia/config.py", line 894, in _build_mask
    regex = re.compile(arguments[0])
  File "/usr/lib/python3.10/re.py", line 251, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/lib/python3.10/sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
fractal% 

```

**Comment by petersilva** [comment]
ugh... it's just bad user input... have to wrap in a try/except and print a reasonable message... no big deal.

explanation:   *.qty is not a properly formed regular expression, it's a glob... accept/reject expects regexes, that's why the crash happens.   change it to .*.qty and it is fine.

**Comment by petersilva** [comment]
when you see that message, correct the pattern to a valid regex, and it will be fine. still bad, but can be fixed.

**Comment by petersilva** [comment]
called it a blocker because it crashes sr3 completely.

**Comment by petersilva** [comment]
with the patch:

```bash
aspypas@srdev1:~/Sarracenia/sr3$ git pull
Already up to date.
aspypas@srdev1:~/Sarracenia/sr3$ sr3 status
2023-05-29 14:41:59,927 8468 [ERROR] sarracenia.credentials isValid credential not found
2023-05-29 14:41:59,927 8468 [CRITICAL] root _validate_urlstr bad credential amqp://tsub@localhost
2023-05-29 14:41:59,927 8468 [ERROR] sarracenia.config _parse_binding broker needed before subtopic
2023-05-29 14:41:59,928 8468 [CRITICAL] sarracenia.config _build_mask invalid regular expression: *.qty, ignored.
status:
Component/Config                         Processes   Connection        Lag                Rates

                                         State   Run Retry  msg data   LagMax  LagAvg  %rej     pubsub   messages     RxData     TxData
                                         -----   --- -----  --- ----   ------  ------  ----   --------       ----     ------     ------
cpost/hd_local                           stop    0/0     0  -1%   0%    0.00s    0.00s  0.0%  0 Bytes/s   0 msgs/s  0 Bytes/s  0 Bytes/s
cpost/my_products                        stop    0/0          -          -         -     -          -        -
poll/airnow_man_pxpaz3                   stop    0/0          -          -         -     -          -        -
poll/ecmwf_grib_https                    stop    0/0     0  -1%   0%    0.00s    0.00s  0.0%  0 Bytes/s   0 msgs/s  0 Bytes/s  0 Bytes/s
poll/noaa_ncep_lam                       stop    0/0     0  -1%   0%    0.00s    0.00s  0.0%  0 Bytes/s   0 msgs/s  0 Bytes/s  0 Bytes/s
poll/rwin_qc_pxpaz3                      stop    0/0     0  -1%   0%    0.00s    0.00s  0.0%  0 Bytes/s   0 msgs/s  0 Bytes/s  0 Bytes/s
sender/hd_upload_to_fex                  stop    0/0     0  -1%   0%    0.00s    0.00s  0.0%  0 Bytes/s   0 msgs/s  0 Bytes/s  0 Bytes/s
subscribe/hd_download_from_fex           stop    0/0          -          -         -     -          -        -
subscribe/hpfx_amis                      stop    0/0     0  -1%   0%    0.00s    0.00s  0.0%  0 Bytes/s   0 msgs/s  0 Bytes/s  0 Bytes/s
subscribe/hungry                         stop    0/0          -          -         -     -          -        -
subscribe/their_feed                     stop    0/0     0  -1%   0%    0.00s    0.00s  0.0%  0 Bytes/s   0 msgs/s  0 Bytes/s  0 Bytes/s
      Total Running Configs:   0 ( Processes: 0 missing: 0 stray: 0 )
                     Memory: uss:0 Bytes rss:0 Bytes vms:0 Bytes
                   CPU Time: User:0.00s System:0.00s
           Pub/Sub Received: 0 msgs/s (0 Bytes/s), Sent:  0 msgs/s (0 Bytes/s)
              Data Received: 0 Files/s (0 Bytes/s), Sent: 0 Files/s (0 Bytes/s)
aspypas@srdev1:~/Sarracenia/sr3$

```

**Comment by petersilva** [comment]
why is it done this way (this way being: print an error message and go on.)

If we abort parsing the file, then all configs are busted as soon as one error in one config is found, impractical.
Would rather that:

  * want to find multiple/all errors that exist rather than just the first one.
  * want to keep ability to view overall status, in spite of individual configuration errors/issues.

There is an issue with error messages being suppressed during config parsing... because all files are parse twice
(once by launcher, once by instance.) so there is probably room for a separate issue about re-engineering how
error messages are generated.

**Comment by petersilva** [comment]
It might be good to flag a configuration as 'broken' if an error is found in it, and refuse to start it up in that case.
opened #688

**Comment by petersilva** [comment]
yay!
