### ISSUE TITLE
python producer api broken...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#681]
example poisting got broken at some point...

```

blacklab% python3 examples/moth_api_producer.py
cfg: <sarracenia.config.Config object at 0x7f38684e3c10>
2023-05-23 16:48:10,570 [INFO] sarracenia.moth.amqp __putSetup exchange declared: xpublic (as: amqp://tfeed@localhost)
Traceback (most recent call last):
  File "/home/peter/Sarracenia/sr3/sarracenia/examples/moth_api_producer.py", line 39, in <module>
    m = sarracenia.Message.fromFileData(sample_fileName, cfg, sarracenia.stat(sample_fileName))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Sarracenia/sr3/sarracenia/__init__.py", line 469, in fromFileData
    m = sarracenia.Message.fromFileInfo(path, o, lstat)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/peter/Sarracenia/sr3/sarracenia/__init__.py", line 514, in fromFileInfo
    msg.updatePaths(o, os.path.dirname(path), os.path.basename(path))
  File "/home/peter/Sarracenia/sr3/sarracenia/__init__.py", line 682, in updatePaths
    if options.post_topicPrefix:
       ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Config' object has no attribute 'post_topicPrefix'. Did you mean: 'topicPrefix'?
blacklab% 
```

fix the problem, and add the examples to the CI/CD so we will notice immediately if it breaks again.

**Comment by petersilva** [comment]
1c81c183bc124195f79d1d2f9972050df66162a9 fixes to examples to work with new
tests in sr_insects that test the API.

**Comment by petersilva** [comment]
OK I was imagining that the CI/CD was fixed... after much faffing:
* the API for publishing had    (broker, properties) as arguments, but often properlties contained 'broker' and looking through the api, there were implementation weirdnesses where sometimes the broker was used, and sometimes the broker property was used.  It is confusing and redundant, so rationalized it.
* now the only argument to the factory methods is properties/options which must include a 'broker' field.  instead of a separate 'broker' argument.
* so this is a breaking change for the API... have to update all the documentation... ugh...

**Comment by petersilva** [comment]
after this gets merged, the "maint" tests should start passing.

**Comment by petersilva** [comment]
Another issue, started looking at api_flow_demo, and it was failing.  Error was *novipFilename* option not being initialized.  that setting is provided by the fill_missing_options that was typically called in the normal code before running a config, but was not recommended as part of the public API.  there was already a hacky looking setting in the example:
```

 cfg.pid_filename = sarracenia.config.get_pid_filename( None, cfg.component, cfg.config, 0)

```

would have had to add another *patch* for this novipFilename setting.  It seems to make more sense to add a call to "fill_missing_options()" instead.  Changed the name of "fill_missing_options()" to "finalize()" and started documenting it.   Call it from the example and can now remove the pid_filename setip... it is more natural and concise.
So the above line is replaced with:

```

cfg.finalize()

```

**Comment by petersilva** [comment]
that we needed the above changes highlighted that the flow_api_demo.py was also broken.  So need to add that to the CI/CD.

**Comment by petersilva** [comment]
everything is merged. should be fixed now.
