### ISSUE TITLE
All redis flow tests fail... 

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#690]
redis flow tests broke because:

```

2023-05-29 04:18:13,550 [DEBUG] sarracenia.flow loadCallbacks registering sarracenia.flowcb.gather.message.Message/please_stop
2023-05-29 04:18:13,550 [DEBUG] sarracenia.flow loadCallbacks registering sarracenia.flowcb.gather.message.Message/metricsReport
2023-05-29 04:18:13,837 [DEBUG] sarracenia.redisqueue __init__ name=work_retry logLevel=debug
2023-05-29 04:18:13,866 [CRITICAL] sarracenia.flow loadCallbacks flowCallback plugin sarracenia.flowcb.retry.Retry did not load: AbstractConnection.__init__() got an unexpected keyword argument 'ssl_cert_reqs'
2023-05-29 04:18:13,866 [DEBUG] sarracenia.flow loadCallbacks details:
Traceback (most recent call last):
  File "/home/runner/.local/lib/python3.10/site-packages/redis/connection.py", line 1450, in get_connection
    connection = self._available_connections.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/runner/work/sarracenia/sarracenia/sarracenia/flow/__init__.py", line 217, in loadCallbacks
    plugin = sarracenia.flowcb.load_library(c, self.o)
  File "/home/runner/work/sarracenia/sarracenia/sarracenia/flowcb/__init__.py", line 255, in load_library
    plugin = class_(opt)
  File "/home/runner/work/sarracenia/sarracenia/sarracenia/flowcb/retry.py", line 56, in __init__
    self.download_retry = RedisQueue(options, 'work_retry')
  File "/home/runner/work/sarracenia/sarracenia/sarracenia/redisqueue.py", line 106, in __init__
    self.redis.set(self.key_name_lasthk, self.now)
  File "/home/runner/.local/lib/python3.10/site-packages/redis/commands/core.py", line 2313, in set
    return self.execute_command("SET", *pieces, **options)
  File "/home/runner/.local/lib/python3.10/site-packages/redis/client.py", line 1266, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/runner/.local/lib/python3.10/site-packages/redis/connection.py", line 1452, in get_connection
    connection = self.make_connection()
  File "/home/runner/.local/lib/python3.10/site-packages/redis/connection.py", line 1492, in make_connection
    return self.connection_class(**self.connection_kwargs)
  File "/home/runner/.local/lib/python3.10/site-packages/redis/connection.py", line 956, in __init__
    super().__init__(**kwargs)
TypeError: AbstractConnection.__init__() got an unexpected keyword argument 'ssl_cert_reqs'

```

**Comment by petersilva** [comment]
@gcglinton I finally had time to take a look at why redis tests are failing, I found this... does it look obvious to you?
I will look at it now.

**Comment by petersilva** [comment]
hmm... should I just leave the SSL off, or should we try to fix it?

**Comment by gcglinton** [comment]
I think having authentication and TLS enabled for testing is of very low value, and just provides more ways that the test can go wrong.

When you deploy SR3 with any Redis stuff, then yes, I think doing both TLS and authentication makes perfect sense, so maybe some docs should be added to reflect that fact.

**Comment by petersilva** [comment]
fair enough... it is excluded from http as well, so that's a consistent approach with other tests.

**Comment by petersilva** [comment]
sigh... they were working for one day, and broke again... no idea what gives.

**Comment by petersilva** [comment]
I did some git bisection, and there isn't a breaking commit, the original fix done brought things from 0% pass rate in all tests to 100% in most tests, and 1 or two tests failing in the failure/recovery tests (flakey and restart.) so disabling redis from the v03_wip commits for now.

I think when I originally evaluated, I was so encouraged by the like 0-90% improvement, that I just assumed that the one or two fails were like other cases, where they were one offs that a repeat would fix, but  they aren't like the other ones... They reliably fail, where the others were just a little intermittent.

The intermittence of the other cases has been reduced by additional work on other issues, and is almost completely gone now (found issues with timing of noticing files and their processing) the tests in question are completely self-contained and there is no good reason for them not to be completely repeatable.

There is also some issues with the integration tests not testing the correct branch... giving misleading results.  I will fix that.

These tests provide some information, but additional unit tests are welcome, and additional flow tests are also welcome.  The existing tests are going to be re-factored into the sr3-examples repository, which should make it easier to build new integration tests.

unit tests... nothing stopping people from building on @gcglinton's work already done.

**Comment by reidsunderland** [comment]
This is sad, but we just don't have time to work on it, so we're going to disable the failing Redis flow tests on GitHub.

**Comment by gcglinton** [comment]
IMO, unless you're planning on using Redis in your real deployments, disabling the tests isn't an issue.

Even then, the unit tests for Redis/disk are all there, and should provide some assurances that those drivers are working as expected, even if the full integration tests aren't.

**Comment by reidsunderland** [comment]
Yeah, we're still not using it anywhere yet. We would like to eventually, but haven't had enough of a need to prioritize it. We're using the S3 and Azure transfer classes though, thank you for those :)

**Comment by gcglinton** [comment]
Happy to hear it!!
