### ISSUE TITLE
discard option broken

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#695]
when discard option is set, there is a crash on startup:

```bash
2023-06-08 00:00:04,329 [INFO] 449460 sarracenia.config finalize overriding batch for consistency with messageCountMax: 3
2023-06-08 00:00:04,331 [INFO] 449460 sarracenia.config finalize overriding batch for consistency with messageCountMax: 3
Traceback (most recent call last):
  File "/home/peter/Sarracenia/sr3/sarracenia/instance.py", line 242, in <module>
    i.start()
  File "/home/peter/Sarracenia/sr3/sarracenia/instance.py", line 231, in start
    self.running_instance = Flow.factory(cfg)
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/__init__.py", line 117, in factory
    return sc(cfg)
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/subscribe.py", line 16, in __init__
    super().__init__(options)
  File "/home/peter/Sarracenia/sr3/sarracenia/flow/__init__.py", line 181, in __init__
    ('sarracenia.flowcb.work.delete.Delete' not in self.plugins_late['load']):
AttributeError: 'Subscribe' object has no attribute 'plugins_late'
2023-06-08 00:00:04,362 449457 [CRITICAL] root run_command subprocess.run failed err=Command '['/usr/bin/python3', '/home/peter/Sarracenia/sr3/sarracenia/instance.py', '--no', '0', '--debug', 'foreground', 'subscribe/hpfx_amis']' returned non-zero exit status 1.
2023-06-08 00:00:04,362 449457 [DEBUG] root run_command Exception details:
Traceback (most recent call last):
  File "/home/peter/Sarracenia/sr3/sarracenia/sr.py", line 1173, in run_command
    subprocess.run(cmd_list, check=True)
  File "/usr/lib/python3.10/subprocess.py", line 524, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/home/peter/Sarracenia/sr3/sarracenia/instance.py', '--no', '0', '--debug', 'foreground', 'subscribe/hpfx_amis']' returned non-zero exit status 1.

```

**Comment by petersilva** [comment]
part of v3.0.41
