### ISSUE TITLE
sr3 downloads fail when the downloaded size doesn't match the size in the message

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#709]
In some cases, the code reaches this call: https://github.com/MetPX/sarracenia/blob/459cc4e726e5a84d76db9f1930a3634d1456f966/sarracenia/flow/__init__.py#L1890

when `new_file` does not exist because the inflight file hasn't been renamed to new_file.

```log
2023-06-26 18:24:40,024 [WARNING] sarracenia.flow do_download downloading again, attempt 3
2023-06-26 18:24:40,024 [DEBUG] sarracenia.flow download https_transport download relPath=/outgoing/OMTO3/OMI-Aura_L2-OMTO3_2023m0626t1352-o100778_v883-2023m0626t165246.he5
2023-06-26 18:24:40,024 [DEBUG] sarracenia.flow download baseUrl.path= /
 --
2023-06-26 18:24:40,026 [DEBUG] sarracenia.transfer.https __open__ bearer_token: c3NjaHBjOmMzTmpMbWh3WXkxamFIQXVjM0JqUUdOaGJtRmtZUzVqWVE9PToxNjQ3Mzc0MjMyOmU2M2RiMDY5YWI3ODA1N2QwZTBmYTBiMTNhOWExYjkyYTg5NjI5ZmI
2023-06-26 18:24:40,174 [DEBUG] sarracenia.transfer read_write sr_proto read_write
2023-06-26 18:24:43,684 [WARNING] sarracenia.flow download downloaded 33214240 of with no length given for OMI-Aura_L2-OMTO3_2023m0626t1352-o100778_v883-2023m0626t165246.he5.tmp assuming ok
2023-06-26 18:24:43,684 [DEBUG] sarracenia.flow download Exception details:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 1871, in download
    self.set_local_file_attributes(new_file, msg)
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 2263, in set_local_file_attributes
    x.set('mtime', sarracenia.timeflt2str(os.path.getmtime(local_file)))
  File "/usr/lib/python3.6/genericpath.py", line 55, in getmtime
    return os.stat(filename).st_mtime
 FileNotFoundError: [Errno 2] No such file or directory: 'OMI-Aura_L2-OMTO3_2023m0626t1352-o100778_v883-2023m0626t165246.he5'
 2023-06-26 18:24:43,685 [WARNING] sarracenia.flow download failed to write OMI-Aura_L2-OMTO3_2023m0626t1352-o100778_v883-2023m0626t165246.he5.tmp: [Errno 2] No such file or directory: 'OMI-Aura_L2-OMTO3_2023m0626t1352-o100778_v883-2023m0626t165246.he5'
2023-06-26 18:24:43,685 [DEBUG] sarracenia.transfer.https close sr_http close
2023-06-26 18:24:43,685 [DEBUG] sarracenia.transfer.https init sr_http init
2023-06-26 18:24:43,688 [INFO] sarracenia.flow do_download attempt 3 failed to download https://omisips1.omisips.eosdis.nasa.gov///outgoing/OMTO3/OMI-Aura_L2-OMTO3_2023m0626t1352-o100778_v883-2023m0626t165246.he5 to /apps/sarra/public_data/20230626/NASA/OMTO3/OMI-Aura_L2-OMTO3_2023m0626t1352-o100778_v883-2023m0626t165246.he5
2023-06-26 18:24:43,688 [ERROR] sarracenia.flow do_download gave up downloading for now, appending to retry queue
2023-06-26 18:24:43,688 [DEBUG] sarracenia.flow.sarra do processing 0 messages worked!
```

This is the relevant section of code where renaming _sometimes_ occurs:

https://github.com/MetPX/sarracenia/blob/459cc4e726e5a84d76db9f1930a3634d1456f966/sarracenia/flow/__init__.py#L1821-L1869

I think the issue is that the file is only renamed from new_inflight_path to new_file when len_written == block_length. But there's three (of four) other cases where it should also rename the file - every case except where False is returned:

https://github.com/MetPX/sarracenia/blob/459cc4e726e5a84d76db9f1930a3634d1456f966/sarracenia/flow/__init__.py#L1848-L1867

**Comment by reidsunderland** [comment]
I think `contentType` also needs to be set in the same cases where the file should be renamed.

**Comment by reidsunderland** [comment]
and this should probably outdented one line. `msg['size']` should be set when block_length == 0? 

https://github.com/MetPX/sarracenia/blob/459cc4e726e5a84d76db9f1930a3634d1456f966/sarracenia/flow/__init__.py#L1869

**Comment by petersilva** [comment]
looks good!  do you want me to cherry-pick that into v03_wip?

**Comment by reidsunderland** [comment]
that's good :) I wasn't 100% sure if this was a bug or if I was just misunderstanding the intended behaviour. The flow tests passed on my system but I'll create a PR to make sure they work on GitHub too.

**Comment by petersilva** [comment]
one of the things I am puzzling over. I think what you have done is right, however the reason why "size" became an optional element of messages was to accomodate people advertising API's where the actual result is not defined and may change over time, so there is no precisely defined correct download result.  This was an argument that led to removing checksum and size from the messages.

So the question is, when we download stuff, should we always assign size? certainly we should if we are forwarding what we downloaded (as in downstream clients will be consuming from us) then it makes sense for us to say at least what we downloaded, and put a size and a checksum on it.  I think that we should... and that is what you are doing... I think it is right... but I'm not quite sure.

**Comment by reidsunderland** [comment]
This also is an issue when the size in the incoming message is wrong, like when we poll a server that reports file sizes in human readable units like 50MB or 1GB. The file size we download is likely slightly different. If we're re-publishing that file, we want to post messages with the real size, not the estimate.
