### ISSUE TITLE
Crash when plugin declares a duration option without a default value

### ISSUE THREAD

**Issue by reidsunderland** [MetPX/sarracenia#712]
When a plugin declares a duration option without a default value (and the option isn't set in the config file):

```
2023-06-29 21:01:38,044 [DEBUG] 56762 sarracenia.flow loadCallbacks details:
Traceback (most recent call last):
  File "/home/ib/dads/ras/sr3/sarracenia/flow/__init__.py", line 222, in loadCallbacks
    plugin = sarracenia.flowcb.load_library(c, self.o)
  File "/home/ib/dads/ras/sr3/sarracenia/flowcb/__init__.py", line 255, in load_library
    plugin = class_(opt)
  File "/users/dor/aspy/ras/.config/sr3/plugins/poll/poll_NASA_CMR.py", line 195, in __init__
    self.o.add_option('temporalNowMinus',    kind='duration') # TODO document, test
  File "/home/ib/dads/ras/sr3/sarracenia/config.py", line 1001, in add_option
    setattr(self, option, durationToSeconds(v,default_value))
  File "/home/ib/dads/ras/sr3/sarracenia/__init__.py", line 265, in durationToSeconds
    if str_value.lower() in [ 'none', 'off', 'false' ]:
AttributeError: 'NoneType' object has no attribute 'lower'
```

Plugin code that caused the issue:

```python
class Poll_nasa_cmr(FlowCB):
    def __init__(self, options):
        super().__init__(options, logger)
        logger.debug("plugin: Poll_NASA_CMR __init__")

        self.o.add_option('temporalNowMinus',    kind='duration')
```

If `durationToSeconds` receives `str_value = None`, should it return 0.0? 

https://github.com/MetPX/sarracenia/blob/459cc4e726e5a84d76db9f1930a3634d1456f966/sarracenia/__init__.py#L251-L284

**Comment by petersilva** [comment]
looks like a good fix. Please submit a pull request.
