### ISSUE TITLE
sr_message missing attribute event

### ISSUE THREAD

**Issue by andreleblanc11** [MetPX/sarracenia#715]
While testing the AM server plugin with ddsr-dev cluster, we've encountered the following error on sarracenia V2.

We think that this might be caused by a missing case in one of the if/else clauses leading up to the file download.

```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 1761, in run
    ok = self.process_message()
  File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 943, in process_message
    ok = self.__do_tasks__()
  File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 422, in __do_tasks__
    if not plugin(self): return False
  File "/usr/lib/python3/dist-packages/sarra/sr_subscribe.py", line 1232, in doit_download
    if self.msg.event == 'delete' :
AttributeError: 'sr_message' object has no attribute 'event'
```

**Comment by petersilva** [comment]
I guess question is, do we do an emergency fix for this (v2 is fairly tranquil... no release likely in near future.)
just wait a bit... dunno.

**Comment by petersilva** [comment]
it made it to v2.23.07
