### ISSUE TITLE
 sr3 status crashes:   if len(self.states[c][cfg]['instance_pids']) >= 0: KeyError: 'instance_pids'

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#724]
no sr3 commands complete when some status files are missing:
```

fractal% sr3 status
Traceback (most recent call last):
  File "/home/peter/.local/bin/sr3", line 33, in <module>
    sys.exit(load_entry_point('metpx-sr3', 'console_scripts', 'sr3')())
  File "/home/peter/Sarracenia/sr3/sarracenia/sr.py", line 2610, in main
    gs = sr_GlobalState(cfg, cfg.configurations)
  File "/home/peter/Sarracenia/sr3/sarracenia/sr.py", line 1109, in __init__
    self._resolve()
  File "/home/peter/Sarracenia/sr3/sarracenia/sr.py", line 871, in _resolve
    if len(self.states[c][cfg]['instance_pids']) >= 0:
KeyError: 'instance_pids'

```

**Comment by petersilva** [comment]
PR #725
