### ISSUE TITLE
Bug file error traceback - on startup and loading a plugin

### ISSUE THREAD

**Issue by iMacadan** [MetPX/sarracenia#784]
```py
2023-10-18 15:52:01,877 [INFO] sarracenia.flow close flow/close completed cleanly pid: 34672 sender/wxo-dev-be03-wxapp-minify instance: 1
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/handlers.py", line 72, in emit
    self.doRollover()
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 32, in doRollover
    super().doRollover()
  File "/usr/lib/python3.6/logging/handlers.py", line 398, in doRollover
    for s in self.getFilesToDelete():
  File "/usr/lib/python3.6/logging/handlers.py", line 363, in getFilesToDelete
    result = result[:len(result) - self.backupCount]
TypeError: slice indices must be integers or None or have an __index__ method
Call stack:
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 242, in <module>
    i.start()
  File "/usr/lib/python3/dist-packages/sarracenia/instance.py", line 233, in start
    self.running_instance.run()
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 381, in run
    if not self.loadCallbacks(self.plugins['load']):
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 228, in loadCallbacks
    logger.info( f'flowCallback plugins to load: {plugins_to_load}' )
Message: "flowCallback plugins to load: ['sarracenia.flowcb.gather.message.Message', 'sarracenia.flowcb.retry.Retry', 'sarracenia.flowcb.housekeeping.resources.Resources', 'rename.msg_rm_sundew_ext_from_tilde', 'rename.msg_rm_minify_from_filename', 'log']"
Arguments: ()
2023-10-18 15:52:09,922 [INFO] sarracenia.flow loadCallbacks flowCallback plugins to load: ['sarracenia.flowcb.gather.message.Message', 'sarracenia.flowcb.retry.Retry', 'sarracenia.flowcb.housekeeping.resources.Resources', 'rename
```

**Comment by petersilva** [comment]
It looks like a problem with config parsing ofr backupCount... being a string... when it should be a number.

**Comment by petersilva** [comment]
logRotateCount is not declared as a count... config.py problem.

**Comment by petersilva** [comment]
this is the result of a startup:

```
sr3 foreground sarra/*minify*

```

the foreground start up logic looks for a config for sarra/*minify (without resolving it.) and fails to find it, which is why the setting is missing.
