### ISSUE TITLE
basic flow test always fails on github.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#809]
works fine on my PC, but:  flow_api_consumer.py doesn't get the messages it should, and neither does flow_api_producer.py.

Running the tests on my development PC, they pass, no issues.

**Comment by petersilva** [comment]
with a tmate session, found the reason for the failure:

```

 %d
2023-11-04 17:40:35,508 [INFO] sarracenia.flowcb.log after_work downloaded ok: /tmp/flow_demo/20231104/WXO-DD/observations/swob-ml/20231104/CWLG/2023-11-04-1700-CWLG-AUTO-swob.xml 
Traceback (most recent call last):
  File "/home/runner/sr_insects/static_flow/./flow_api_consumer.py", line 35, in <module>
    subscriber.run()
  File "/home/runner/work/sarracenia/sarracenia/sarracenia/flow/__init__.py", line 554, in run
    with open(self.o.metricsFilename, 'w') as mfn:
FileNotFoundError: [Errno 2] No such file or directory: '/home/runner/.cache/sr3/metrics/subscribe_flow_demo_00.json'
runner@fv-az1493-508:~/sr_insects/static_flow$ 
```
