### ISSUE TITLE
sr_subscribe gives bogus SSL failure message...

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#81]
it seems harmless, but on startup, sr_subscribe, when consuming the first message, and one is connecting to an SSL broker, will print:

```
Exception ignored in: <bound method _AbstractTransport.__del__ of <amqplib.client_0_8.transport.SSLTransport object at 0x7fca748f42e8>>
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/amqplib/client_0_8/transport.py", line 97, in __del__
    self.close()
  File "/usr/lib/python3/dist-packages/amqplib/client_0_8/transport.py", line 139, in close
    self.sock.shutdown(socket.SHUT_RDWR)
  File "/usr/lib/python3.6/ssl.py", line 1047, in shutdown
    socket.shutdown(self, how)

```
have looked at the code, and this message is generated here on the line assigning ts
variable in sr_message.py:set_msg_time:

```
        parts       = self.time.split('.')
        ts          = time.strptime(parts[0]+" +0000", "%Y%m%d%H%M%S %z" )
        ep_msg      = calendar.timegm(ts)
 
```       
Processing continues fine, seems to have no ill effect, but very strange.

**Comment by michelgrenier** [comment]
I dont understand how it can relate to that code snippet. To me it looks like logging out of the looping connection attempts (must connect to the broker in sr_amqp).  And  one attempt failed...

**Comment by reidsunderland** [comment]
This is very likely fixed, I've never seen it. I'm trying to clean up some old issues
