### ISSUE TITLE
sr3 disable when nothing running... crashes.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#825]
silvap@di-configs:\~/gitlab/sr3-dev-config/ddsr-dev/poll\$
silvap@di-configs:\~/gitlab/sr3-dev-config/ddsr-dev/poll\$ sr3d disable
Data Pump Name: ddsr-dev. DSH Machine List: /fs/isilon-eccc13/ssc/hpcdi/silvap/gitlab/sr3-dev-config/_dsh_config/ddsr-dev.list
ddsr-cmc-dev01: 2023-11-15 16:52:05,051 21895 [INFO] root disable cpost/msc-radar
ddsr-cmc-dev01: Traceback (most recent call last):
ddsr-cmc-dev01:   File "/usr/bin/sr3", line 11, in <module>
ddsr-cmc-dev01:     load_entry_point('metpx-sr3==3.0.46', 'console_scripts', 'sr3')()
ddsr-cmc-dev01:   File "/local/home/sarra/sr3/sarracenia/sr.py", line 2822, in main
ddsr-cmc-dev01:     gs.disable()
ddsr-cmc-dev01:   File "/local/home/sarra/sr3/sarracenia/sr.py", line 1349, in disable
ddsr-cmc-dev01:     if len(self.states[c][cfg]['instance_pids']) > 0:
ddsr-cmc-dev01: KeyError: 'instance_pids'
ddsr-cmc-dev02: 2023-11-15 16:52:06,736 53594 [INFO] root disable cpost/msc-radar
ddsr-cmc-dev02: Traceback (most recent call last):
ddsr-cmc-dev02:   File "/usr/bin/sr3", line 11, in <module>
ddsr-cmc-dev02:     load_entry_point('metpx-sr3==3.0.46', 'console_scripts', 'sr3')()
ddsr-cmc-dev02:   File "/usr/lib/python3/dist-packages/sarracenia/sr.py", line 2871, in main
ddsr-cmc-dev02:     gs.disable()
ddsr-cmc-dev02:   File "/usr/lib/python3/dist-packages/sarracenia/sr.py", line 1395, in disable
ddsr-cmc-dev02:     if len(self.states[c][cfg]['instance_pids']) > 0:
ddsr-cmc-dev02: KeyError: 'instance_pids'
silvap@di-configs:~/gitlab/sr3-dev-config/ddsr-dev/poll$

**Comment by petersilva** [comment]
OK, so seeing this on the server, I did these quick patches:
* 0343d5e02af630291cc29b8478caff66560f5abc
* b77ca5be3486c4c6eb2ad6cb1f7709b68bd210f1

And then looked at what is the root cause.   The issue here is we are dealing with configurations that may or may not have been used before.  When a configuration is used, a state directory is created, and the routine that initializes these missing keys does it based on the existence of the state directories.  so the value won't be initialized if the state directory doesn't exist.

**Comment by petersilva** [comment]
merged.
