### ISSUE TITLE
crash in config.py when using a custom plugin and variableExpansion with no message.

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#851]
in a poll (so upstream of where a message exists.) need to expand self.o.directory (because it has a date pattern.)
but the thing is crashing with:

```

2023-12-01 19:48:03,779 [ERROR] 34503 sarracenia.flow gather flowCallback plugin <bound method Wiski2.gather of <scheduled.wiski2.Wiski2 object at 0x7efea793c630>> crashed: argument of type 'NoneType' is not iterable
2023-12-01 19:48:03,779 [DEBUG] 34503 sarracenia.flow gather details:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sarracenia/flow/__init__.py", line 1069, in gather
    new_incoming = p()
  File "/local/home/sarra/.config/sr3/plugins/scheduled/wiski2.py", line 167, in gather
    directory=self.o.variableExpansion( self.o.directory )
  File "/usr/lib/python3/dist-packages/sarracenia/config.py", line 2232, in variableExpansion
    if '_matches' in message and len(new_dir.split( '${' )) > 1:
TypeError: argument of type 'NoneType' is not iterable
2023-12-01 19:48:03,780 [DEBUG] 34503 sarracenia.flow filter start len(incoming)=0, rejected=0
2023-12-01 19:48:03,781 [DEBUG] 34503 sarracenia.flow filter end len(incoming)=0, rejected=0
2023-12-01 19:48:03,781 [DEBUG] 34503 sarracenia.flow run B filtered incoming: 0, ok: 0 (directories: 0), rejected: 0, failed:

```

**Comment by petersilva** [comment]
fix for this is in the convert_refuse_to_overwrite branch.

**Comment by petersilva** [comment]
fix is in ... 493c0b1a7079f6dd0bc1e153cbb603357e6d80f3
