### ISSUE TITLE
sr3 overview "Type Error: %d format: a number is required not a tuple"

### ISSUE THREAD

**Issue by petersilva** [MetPX/sarracenia#940]
```
sr3 overview
 .
 .
 .
sarra      mixed      mult    20
        2 disabled: get_dms-products-wxo-minify-i0/1, get_dms-products-wxo-i0/1
      17 running: get-ncp-bulletins-i1/1, get_hydro_quebec_http-i1/1, cvt_sxvd02_to_sxvd62_DEV-i1/1, cvt_rawca_to_bulletin-i1/1, get_copernicus-i1/1, get-ncep-gfs-i1/1, get_noaa_ncep_lam_TEST_OPS-i1/1, get_loggernet-i1/1, get_nasa-i1/1, get_noaa_snodas-i1/1, get_ddi_msc-cmc_global_netcdf-i1/1, get-yukon-files-i1/1, get-WEBPRODS_DEV-i1/1, get_dms-wxo-citypages-i1/1, get-lrgs-data2-i1/1, get_QC_AQ-i1/1, get_wxo_test_marine-i1/1
 1 waitVip: get_wifs_grib-i1/1
 Traceback (most recent call last):
   File "/usr/bin/sr3", line 11, in <module>
   load_entry_point('metpx-sr3==3.0.51rc7', 'console_scripts', 'sr3')()
   File "/usr/lib/python3/dist-packages/sarracenia/sr.py", line 2994, in main
     sys.exit(gs.overview())
   File "/usr/lib/python3/dist-packages/sarracenia/sr.py", line 2783, in overview
     (len(self.configs[c]) - len(status['disabled']),  ', '.join(status['running'] ))) )
 TypeError: %d format: a number is required, not tuple

```

**Comment by petersilva** [comment]
on the machine where it is happenning, it has something to do with senders.
if I do sr3 overview sender/*  it gives the message.
